/**
 * Blocking-gate wiring: writes the files that make `gateforge check`
 * block commits and CI. Shared by `gateforge init --blocking` and
 * `gateforge enforce`. Every write is idempotent and never overwrites
 * user-modified files — a second run always reports "exists, leaving
 * untouched".
 *
 * Engine resolution order: developer override, repository-pinned CLI,
 * recorded engine checkout, explicit engine path, then PATH fallback.
 */
import { chmodSync, existsSync, mkdirSync, readFileSync, writeFileSync } from 'node:fs';
import { join } from 'node:path';
import type { Io } from '../io.js';
import { recordInitPath, writeLine } from '../io.js';
import { VERSION } from './common.js';

/** Marker boundaries for the Gateforge-owned generated wrapper script. */
export const GENERATED_HOOK_MARKER_BEGIN = '// >>> gateforge generated hook v1 >>>';
export const GENERATED_HOOK_MARKER_END = '// <<< gateforge generated hook v1 <<<';

/**
 * Resolves the engine root from the live CLI invocation, when gateforge
 * was started as `<engine>/packages/cli/bin/gateforge.js`. Returns null
 * under test runners / other invocations — the hook then resolves the
 * repository-pinned CLI before trusted paths and global PATH.
 */
export function engineRootFromInvocation(): string | null {
  const entry = process.argv[1] ?? '';
  if (!/packages[\\/]cli[\\/]bin[\\/]gateforge\.js$/.test(entry)) return null;
  return join(entry, '..', '..', '..', '..');
}

const hookScriptTemplate = (gateArgs: readonly string[]): string => `${GENERATED_HOOK_MARKER_BEGIN}
// Cross-platform entry for the blocking static gate (generated by
// \`gateforge\`). Requires Node, like the CLI.
//
// Resolution order: developer override, repository-pinned CLI, recorded
// engine checkout, explicit engine path, then global PATH fallback.
import { existsSync, readFileSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';
import { spawnSync } from 'node:child_process';

const root = resolve(dirname(fileURLToPath(import.meta.url)), '../..');
const args = ${JSON.stringify(gateArgs)};
const winShell = process.platform === 'win32';

function runNode(cliPath) {
  const result = spawnSync(process.execPath, [cliPath, ...args], { cwd: root, stdio: 'inherit' });
  process.exit(result.status ?? 1);
}

// 1. Developer override: an unreleased engine checkout.
if (process.env.GATEFORGE_DEV_ENGINE) {
  const devCli = resolve(root, process.env.GATEFORGE_DEV_ENGINE, 'packages/cli/bin/gateforge.js');
  if (existsSync(devCli)) runNode(devCli);
}

// 2. The repository-pinned devDependency.
const pinned = resolve(root, 'node_modules/@gate-forge/cli/bin/gateforge.js');
if (existsSync(pinned)) runNode(pinned);

// 3. Recorded engine checkout (legacy): only when it exists HERE.
const engineFile = resolve(root, '.gateforge/engine');
const engine = existsSync(engineFile) ? readFileSync(engineFile, 'utf8').trim() : '';
if (engine) {
  const engineCli = resolve(root, engine, 'packages/cli/bin/gateforge.js');
  if (existsSync(engineCli)) runNode(engineCli);
}

// 4. Explicit engine path.
if (process.env.GATEFORGE_CLI) {
  const cli = resolve(root, process.env.GATEFORGE_CLI);
  if (!existsSync(cli)) {
    console.error(\`gateforge: GATEFORGE_CLI does not exist: \${cli}\`);
    process.exit(1);
  }
  runNode(cli);
}

// 5. Global PATH is a visible last-resort fallback only.
{
  console.error('warning: using Gateforge from global PATH; add an exact @gate-forge/cli devDependency to pin this gate');
  const result = spawnSync('gateforge', args, { cwd: root, stdio: 'inherit', shell: winShell });
  if (!result.error) process.exit(result.status ?? 1);
}

console.error('gateforge: CLI not found (install @gate-forge/cli in this repository, or set GATEFORGE_CLI / .gateforge/engine)');
process.exit(1);
${GENERATED_HOOK_MARKER_END}
`;

/** Identifies a Gateforge-owned wrapper, including pre-marker versions. */
function isGeneratedHookScript(body: string): boolean {
  return (
    (body.includes(GENERATED_HOOK_MARKER_BEGIN) && body.includes(GENERATED_HOOK_MARKER_END)) ||
    (body.includes('Cross-platform entry for the blocking static gate (generated by') &&
      body.includes('const args = ') &&
      body.includes('node_modules/@gate-forge/cli'))
  );
}

/** Replaces only the Gateforge-owned block and preserves surrounding text. */
function replaceGeneratedHookBlock(body: string, replacement: string): string {
  const begin = body.indexOf(GENERATED_HOOK_MARKER_BEGIN);
  const end = body.indexOf(GENERATED_HOOK_MARKER_END);
  if (begin < 0 || end < begin) return replacement;
  const suffix = body.slice(end + GENERATED_HOOK_MARKER_END.length);
  const joinedReplacement = replacement.endsWith('\n') && suffix.startsWith('\n') ? replacement.slice(0, -1) : replacement;
  return `${body.slice(0, begin)}${joinedReplacement}${suffix}`;
}

const PRE_COMMIT_BLOCK = `# --- gateforge (generated): blocking static gate ---------------------
  - repo: local
    hooks:
      - id: gateforge-check
        name: gateforge — unresolved findings / unwaived obligations
        entry: node .gateforge/hooks/gateforge-check.mjs
        language: system
        pass_filenames: false
`;

export type GitlabGateMode = 'strict' | 'check';

/** Renders one CI template with the gate command chosen by the wiring command. */
export function renderGitlabCiTemplate(mode: GitlabGateMode = 'check'): string {
  const jobName = mode === 'strict' ? 'gateforge:e2e-gate' : 'gateforge:check';
  const gateSteps =
    mode === 'strict'
      ? [
          '    - |',
          '      if [ "$CI_PIPELINE_SOURCE" = "merge_request_event" ]; then',
          '        base_pipelines=$(curl --silent --show-error --fail --header "JOB-TOKEN: $CI_JOB_TOKEN" "$CI_API_V4_URL/projects/$CI_PROJECT_ID/pipelines?sha=$CI_MERGE_REQUEST_DIFF_BASE_SHA&status=success&per_page=100" 2>/dev/null || true)',
          `        base_pipeline_id=$(printf '%s' "$base_pipelines" | node -e 'let data="";process.stdin.on("data",chunk=>data+=chunk).on("end",()=>{try{const rows=JSON.parse(data);const row=rows.find(item=>item.sha===process.env.CI_MERGE_REQUEST_DIFF_BASE_SHA&&item.source==="push"&&item.ref===process.env.CI_DEFAULT_BRANCH);process.stdout.write(row?String(row.id):"")}catch{}})')`,
          '        if [ -n "$base_pipeline_id" ]; then',
          '          base_jobs=$(curl --silent --show-error --fail --header "JOB-TOKEN: $CI_JOB_TOKEN" "$CI_API_V4_URL/projects/$CI_PROJECT_ID/pipelines/$base_pipeline_id/jobs?per_page=100" 2>/dev/null || true)',
          `          base_job_id=$(printf '%s' "$base_jobs" | node -e 'let data="";process.stdin.on("data",chunk=>data+=chunk).on("end",()=>{try{const rows=JSON.parse(data);const row=rows.find(item=>item.name==="gateforge:e2e-gate"&&item.status==="success");process.stdout.write(row?String(row.id):"")}catch{}})')`,
          '          if [ -n "$base_job_id" ]; then',
          '            mkdir -p .gateforge/test-gates',
          '            if curl --silent --show-error --fail --location --header "JOB-TOKEN: $CI_JOB_TOKEN" "$CI_API_V4_URL/projects/$CI_PROJECT_ID/jobs/$base_job_id/artifacts/.gateforge/test-gates/receipt.json" --output .gateforge/test-gates/receipt.json && curl --silent --show-error --fail --location --header "JOB-TOKEN: $CI_JOB_TOKEN" "$CI_API_V4_URL/projects/$CI_PROJECT_ID/jobs/$base_job_id/artifacts/.gateforge/test-gates/execution-result.json" --output .gateforge/test-gates/execution-result.json; then',
          '              echo "Gateforge CI: downloaded exact merge-base receipt artifact"',
          '            else',
          '              echo "Gateforge CI: merge-base receipt artifact unavailable; carry-forward disabled"',
          '            fi',
          '          fi',
          '        fi',
          '      fi',
          '    - |',
          '      if [ "$CI_PIPELINE_SOURCE" = "merge_request_event" ]; then',
          '        run_gateforge test-gates --changed --scope changed',
          '      else',
          '        run_gateforge test-gates --changed',
          '      fi',
          '    - run_gateforge check --changed --candidate-commit "$CI_COMMIT_SHA" --require-e2e',
        ].join('\n')
      : '    - run_gateforge check --changed --candidate-commit "$CI_COMMIT_SHA"';
  const artifacts =
    mode === 'strict'
      ? [
          '  artifacts:',
          '    when: always',
          '    paths:',
          '      - .gateforge/test-gates/report.json',
          '      - .gateforge/test-gates/receipt.json',
          '      - .gateforge/test-gates/execution-result.json',
          '    expire_in: 90 days',
        ].join('\n')
      : '';
  return `# Generated by Gateforge ${VERSION}. Add @gate-forge/cli at exactly ${VERSION} to the root package.
# If the Playwright config imports packages from nested Node projects, list their
# space-separated relative directories in GATEFORGE_CI_NESTED_PACKAGE_DIRS below.
# The job uses a frozen lockfile when available and the manifest when it is not.
# This job does not protect itself. Use Protected branches; require Pipelines must succeed.
# Use an organization pipeline execution policy for candidate CI.
# APPROVED POLICY PIN: GATEFORGE_APPROVED_POLICY_DIGEST must match owner policy.
# Strict mode needs GATEFORGE_WITNESS_VERIFIER_KEY and GATEFORGE_APPROVED_POLICY_DIGEST
# from protected owner-managed variables. A policy mismatch blocks as ENFORCEMENT_UNTRUSTED.
# Existing generated files are left untouched; review and replace them yourself.
${jobName}:
  stage: test
  image: node:22
  variables:
    GATEFORGE_VERSION: "${VERSION}"
    GATEFORGE_CI_NESTED_PACKAGE_DIRS: ""
  script:
    - |
      set -eu
      set -f
      install_node_package() {
        package_dir="$1"
        if [ ! -f "$package_dir/package.json" ]; then
          echo "Gateforge CI: package.json not found in $package_dir" >&2
          return 1
        fi
        if [ -f "$package_dir/pnpm-lock.yaml" ]; then
          corepack pnpm --dir "$package_dir" install --frozen-lockfile
        elif [ -f "$package_dir/yarn.lock" ]; then
          corepack yarn --cwd "$package_dir" install --frozen-lockfile
        elif [ -f "$package_dir/package-lock.json" ] || [ -f "$package_dir/npm-shrinkwrap.json" ]; then
          npm ci --prefix "$package_dir"
        else
          npm install --prefix "$package_dir"
        fi
      }
      install_node_package .
      for package_dir in $GATEFORGE_CI_NESTED_PACKAGE_DIRS; do
        case "$package_dir" in
          /*|..|../*|*/..|*/../*) echo "Gateforge CI: nested package path must stay inside the repository: $package_dir" >&2; exit 1 ;;
        esac
        install_node_package "$package_dir"
      done
      run_gateforge() {
        if [ -f pnpm-lock.yaml ]; then
          corepack pnpm exec gateforge "$@"
        elif [ -f yarn.lock ]; then
          corepack yarn run gateforge "$@"
        else
          if [ ! -x node_modules/.bin/gateforge ]; then
            echo "Gateforge CI: install @gate-forge/cli as an exact root devDependency" >&2
            return 1
          fi
          node_modules/.bin/gateforge "$@"
        fi
      }
      actual_version=$(run_gateforge --version)
      if [ "$actual_version" != "$GATEFORGE_VERSION" ]; then
        echo "Gateforge CI: expected $GATEFORGE_VERSION but installed $actual_version" >&2
        exit 1
      fi
      echo "Gateforge CI: using pinned Gateforge $actual_version"
${gateSteps}
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
    - if: $CI_PIPELINE_SOURCE == "push" && $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
${artifacts}
`;
}

/**
 * Renders the strict GitHub Actions workflow and keeps secrets in the
 * protected workflow environment.
 *
 * Args:
 *   none.
 *
 * Returns:
 *   string: workflow source.
 */
export function renderGithubActionsTemplate(): string {
  return `# Generated by Gateforge ${VERSION}; review before enabling required checks.
name: Gateforge
on:
  pull_request:
  push:
  workflow_dispatch:
permissions:
  contents: read
  actions: read
jobs:
  gateforge:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v4
        with:
          node-version: 22
      - name: Install Gateforge
        run: npm install --no-save --package-lock=false @gate-forge/cli@${VERSION}
      - name: Locate exact merge-base receipt
        if: github.event_name == 'pull_request'
        id: base
        env:
          GH_TOKEN: \${{ github.token }}
        run: |
          base_sha=$(git merge-base "$GITHUB_SHA" "origin/$GITHUB_BASE_REF")
          run_id=$(gh api "repos/$GITHUB_REPOSITORY/actions/workflows/gateforge.yml/runs?head_sha=$base_sha&status=success&per_page=100" --jq '[.workflow_runs[] | select(.event == "push")][0].id // empty')
          printf 'run_id=%s\\n' "$run_id" >> "$GITHUB_OUTPUT"
      - uses: actions/download-artifact@v4
        continue-on-error: true
        with:
          name: gateforge-test-gates
          run-id: \${{ steps.base.outputs.run_id }}
          github-token: \${{ github.token }}
          repository: \${{ github.repository }}
          path: .gateforge/test-gates
      - name: Verify witnessed receipt
        env:
          GATEFORGE_WITNESS_VERIFIER_KEY: \${{ secrets.GATEFORGE_WITNESS_VERIFIER_KEY }}
          GATEFORGE_APPROVED_POLICY_DIGEST: \${{ secrets.GATEFORGE_APPROVED_POLICY_DIGEST }}
        run: |
          if [ "$GITHUB_EVENT_NAME" = "pull_request" ]; then
            ./node_modules/.bin/gateforge test-gates --changed --scope changed
          else
            ./node_modules/.bin/gateforge test-gates --changed
          fi
          ./node_modules/.bin/gateforge check --changed --candidate-commit "$GITHUB_SHA" --require-e2e
      - uses: actions/upload-artifact@v4
        if: github.event_name == 'push' && github.ref_name == github.event.repository.default_branch && success()
        with:
          name: gateforge-test-gates
          path: |
            .gateforge/test-gates/receipt.json
            .gateforge/test-gates/execution-result.json
          if-no-files-found: error
          retention-days: 90
`;
}

/**
 * Writes the generated GitHub Actions workflow only when absent.
 *
 * Args:
 *   io: process context.
 *
 * Returns:
 *   void.
 */
export function writeGithubActionsTemplate(io: Io): void {
  const dir = join(io.cwd, '.github', 'workflows');
  mkdirSync(dir, { recursive: true });
  const path = join(dir, 'gateforge.yml');
  if (!existsSync(path)) {
    writeFileSync(path, renderGithubActionsTemplate());
    recordInitPath(io, io.cwd, path, 'created');
    writeLine(io.stdout, `created: ${path}`);
  } else {
    recordInitPath(io, io.cwd, path, 'preserved');
    writeLine(io.stdout, `exists, leaving untouched: ${path}`);
  }
}

/**
 * Records the engine checkout root in `.gateforge/engine` — the ONE
 * machine-specific reference the generated hook reads. Empty/absent when
 * gateforge resolves from PATH instead (the npm-install future).
 */
export function writeEngineReference(io: Io, engineRoot: string | null): void {
  const path = join(io.cwd, '.gateforge', 'engine');
  if (engineRoot === null) {
    if (existsSync(path)) writeLine(io.stdout, `exists, leaving untouched: ${path}`);
    return;
  }
  if (!existsSync(path)) {
    writeFileSync(path, `${engineRoot}\n`);
    recordInitPath(io, io.cwd, path, 'created');
    writeLine(io.stdout, `created: ${path} (engine checkout root)`);
  } else {
    recordInitPath(io, io.cwd, path, 'preserved');
    writeLine(io.stdout, `exists, leaving untouched: ${path}`);
  }
}

/** Ensures the check-gate hook script exists (executable).
 *
 * Args:
 *   gateArgs: the gate invocation the hook runs, chosen by the wiring
 *     command at generation time — `enforce`/`adopt` wire
 *     ['check', '--changed'] (debt-friendly); `init --blocking` wires
 *     ['check', '--staged', '--require-e2e'] (strict staged gate). One
 *     template, one hook file, one resolution order — only the check
 *     invocation differs, and it is recorded in the generated file.
 */
export function ensureHookScript(
  io: Io,
  engineRoot: string | null,
  gateArgs: readonly string[] = ['check', '--changed'],
): string {
  const hookDir = join(io.cwd, '.gateforge', 'hooks');
  mkdirSync(hookDir, { recursive: true });
  const hookScript = join(hookDir, 'gateforge-check.mjs');
  if (!existsSync(hookScript)) {
    writeFileSync(hookScript, hookScriptTemplate(gateArgs));
    chmodSync(hookScript, 0o755);
    recordInitPath(io, io.cwd, hookScript, 'created');
    writeLine(io.stdout, `created: ${hookScript}`);
  } else {
    recordInitPath(io, io.cwd, hookScript, 'preserved');
    const current = readFileSync(hookScript, 'utf8');
    if (isGeneratedHookScript(current)) {
      const updated = replaceGeneratedHookBlock(current, hookScriptTemplate(gateArgs));
      if (updated !== current) {
        writeFileSync(hookScript, updated, 'utf8');
        chmodSync(hookScript, 0o755);
        writeLine(io.stdout, `updated: ${hookScript} (${gateArgs.join(' ')})`);
      } else {
        writeLine(io.stdout, `verified: ${hookScript} (${gateArgs.join(' ')})`);
      }
    } else {
      writeLine(io.stdout, `exists, leaving untouched: ${hookScript} (foreign file)`);
    }
  }
  return hookScript;
}

/** Appends the gateforge-check hook to .pre-commit-config.yaml (idempotent). */
export function appendPreCommitHook(io: Io): void {
  const path = join(io.cwd, '.pre-commit-config.yaml');
  if (existsSync(path)) {
    const current = readFileSync(path, 'utf8');
    if (current.includes('gateforge-check')) {
      recordInitPath(io, io.cwd, path, 'preserved');
      writeLine(io.stdout, `exists, leaving untouched: ${path} (gateforge-check)`);
      return;
    }
    writeFileSync(path, `${current.endsWith('\n') ? current : current + '\n'}${PRE_COMMIT_BLOCK}`);
    writeLine(io.stdout, `updated: ${path} (gateforge-check hook appended)`);
    return;
  }
  writeFileSync(path, `repos:\n${PRE_COMMIT_BLOCK}`);
  recordInitPath(io, io.cwd, path, 'created');
  writeLine(io.stdout, `created: ${path} (with gateforge-check hook)`);
}

/** Writes the GitLab CI job template + include wiring (idempotent). */
export function writeGitlabCiTemplate(io: Io, mode: GitlabGateMode = 'check'): void {
  const dir = join(io.cwd, '.gateforge', 'ci');
  mkdirSync(dir, { recursive: true });
  const path = join(dir, 'gitlab-gateforge.yml');
  if (!existsSync(path)) {
    writeFileSync(path, renderGitlabCiTemplate(mode));
    recordInitPath(io, io.cwd, path, 'created');
    writeLine(io.stdout, `created: ${path}`);
  } else {
    recordInitPath(io, io.cwd, path, 'preserved');
    writeLine(io.stdout, `exists, leaving untouched: ${path}`);
  }
  const gitlabCi = join(io.cwd, '.gitlab-ci.yml');
  if (!existsSync(gitlabCi)) {
    writeFileSync(gitlabCi, `include:\n  - local: '.gateforge/ci/gitlab-gateforge.yml'\n`);
    recordInitPath(io, io.cwd, gitlabCi, 'created');
    writeLine(io.stdout, `created: ${gitlabCi} (includes the gateforge jobs)`);
    return;
  }
  recordInitPath(io, io.cwd, gitlabCi, 'preserved');
  const current = readFileSync(gitlabCi, 'utf8');
  if (current.includes('gitlab-gateforge.yml')) {
    writeLine(io.stdout, `exists, leaving untouched: ${gitlabCi} (gateforge include present)`);
    return;
  }
  const local = "  - local: '.gateforge/ci/gitlab-gateforge.yml'";
  if (/^include:/m.test(current)) {
    writeFileSync(gitlabCi, current.replace(/^include:[^\n]*/m, (match) => `${match}\n${local}`));
    writeLine(io.stdout, `updated: ${gitlabCi} (gateforge include added under existing include)`);
    return;
  }
  writeFileSync(gitlabCi, `${current.endsWith('\n') ? current : `${current}\n`}include:\n${local}\n`);
  writeLine(io.stdout, `updated: ${gitlabCi} (include appended)`);
}

/**
 * Writes the selected CI provider's template.
 *
 * Args:
 *   io: process context.
 *   provider: GitHub Actions or GitLab CI.
 *   mode: strict or static-check job mode.
 *
 * Returns:
 *   void.
 */
export function writeCiTemplate(io: Io, provider: 'github' | 'gitlab', mode: GitlabGateMode = 'check'): void {
  if (provider === 'github') {
    writeGithubActionsTemplate(io);
  } else {
    writeGitlabCiTemplate(io, mode);
  }
}
/**
 * Prints owner-run steps for making the generated CI job mandatory.
 *
 * Args:
 *   io: process context.
 *
 * Returns:
 *   void.
 */
export function writeServerProtectionInstructions(io: Io): void {
  writeLine(
    io.stdout,
    [
      'Server setup (review and run explicitly; Gateforge does not change branch settings):',
      'GitHub: gh api --method PUT "repos/OWNER/REPO/branches/BRANCH/protection" --input - <<\'JSON\'',
      '{"required_status_checks":{"strict":true,"contexts":["gateforge"]},"enforce_admins":true,"required_pull_request_reviews":null,"restrictions":null}',
      'JSON',
      'GitLab: glab api --method PUT "projects/PROJECT_ID" -f only_allow_merge_if_pipeline_succeeds=true',
      'GitLab: glab api --method POST "projects/PROJECT_ID/protected_branches" -f name=BRANCH -f push_access_level=0 -f merge_access_level=30 -f allow_force_push=false',
    ].join('\n'),
  );
}

/** Wires engine, local hooks, and the selected CI provider. */
export function ensureBlockingWiring(
  io: Io,
  engineRoot: string | null,
  gateArgs: readonly string[] = ['check', '--changed'],
  ciMode: GitlabGateMode = 'check',
  provider: 'github' | 'gitlab' = 'gitlab',
): void {
  writeEngineReference(io, engineRoot);
  ensureHookScript(io, engineRoot, gateArgs);
  appendPreCommitHook(io);
  writeCiTemplate(io, provider, ciMode);
}
