/**
 * The GLOBAL native preparation freeze barrier (contract: "ONE native
 * process, ONE GLOBAL prepared snapshot").
 *
 * Why this exists. A Playwright config's prerequisite (`setup`) projects
 * produce their artifacts — the saved `playwright/.auth/user.json` of the
 * standard auth pattern above all — WHILE the behavioral projects are
 * already scheduled to run. Gateforge's candidate freeze, on the other
 * hand, is taken BEFORE the runner starts, so a run whose setup writes
 * generated bytes into the workspace always ends with a candidate tree
 * that no longer equals the frozen one, and no receipt is ever sealed.
 * That is the honest failure this module removes — not by excluding the
 * generated bytes (that would weaken every binding), but by taking ONE
 * prepared snapshot AFTER the whole prerequisite stage and BEFORE any
 * body project, and then demanding the workspace stay exactly that.
 *
 * The shape of the barrier, and why each part exists:
 *
 * - ONE controller project. The engine adds a project of its own that
 *   depends on the FULL upstream prerequisite closure of the planned
 *   graph, and gives every non-prerequisite planned project that
 *   controller as its FIRST dependency (its own captured edges follow,
 *   unchanged, in their emitted order). Prerequisites keep their edges
 *   exactly as captured. The runner's own phase scheduler then orders
 *   prerequisite → controller → body inside ONE process, with the
 *   runner's real dependency semantics — not a second process, not a flag.
 * - The controller is a real Playwright test, because the environment
 *   leak it has to undo happens in WORKERS: the native scheduler unions
 *   every dependency worker's produced environment into its dependents
 *   (`runner/tasks.js`), so merely emitting an empty controller project
 *   would hand each body the whole preparation environment.
 * - A REQUEST/RELEASE handshake. The controller writes a request naming
 *   the exact run, invocation and per-invocation nonce; the trusted CLI
 *   — the only process holding supervisor credentials — validates every
 *   prerequisite identity against the authenticated witness execution
 *   trace, freezes, and answers with a SIGNED release. A request that
 *   never comes, an unsigned release, a release for another
 *   run/invocation/nonce, and a release whose bound controller spec
 *   bytes no longer hash to what the CLI pinned are all refusals, and a
 *   controller that never receives a valid release fails its own bounded
 *   wait instead of letting the bodies run unfrozen.
 * - An ephemeral Ed25519 signature. A release is a file, and a file at
 *   this boundary is forgeable by any code running as the same user. The
 *   private key is minted per invocation and never leaves the CLI
 *   process — never a child environment, never a file; the controller
 *   receives only the public key. Same-UID modify/restore or in-process
 *   tampering stays OUTSIDE this boundary (this is not a filesystem
 *   sandbox); what the signature closes is an ordinary control-file
 *   forgery and any replay of an older or different release.
 *
 * Honesty boundary (repeated on purpose): this is a CONTROL barrier, not
 * a physical one. It orders one native process, proves the prerequisites
 * really passed under supervision, and proves the workspace did not move
 * between the freeze and the seal. It does not make the source read-only.
 */
import { createHash, createPublicKey, generateKeyPairSync, sign, verify, type KeyObject } from 'node:crypto';
import { chmodSync, existsSync, mkdirSync, readFileSync, rmSync, writeFileSync } from 'node:fs';
import { join } from 'node:path';
import { fileURLToPath } from 'node:url';

/** The engine-owned controller project name (never a candidate project). */
export const FREEZE_CONTROLLER_PROJECT = 'gateforge-freeze';

/** Directory (inside the excluded run-state dir) holding the barrier files. */
export const FREEZE_CONTROL_DIR = 'native-freeze';

/** The generated controller spec: the ONE worker that performs the handshake. */
export const FREEZE_CONTROL_SPEC_FILE = 'freeze-controller.spec.ts';

/** The controller's request document (written by the controller worker). */
export const FREEZE_REQUEST_FILE = 'freeze-request.json';

/** The CLI's signed release document (read by the controller worker). */
export const FREEZE_RELEASE_FILE = 'freeze-release.json';

/**
 * The trusted CLI's REFUSAL document (read by the controller worker).
 *
 * The handshake needs a failure channel as well as a success one, or a
 * permanent refusal turns into a bounded-but-slow timeout: the trusted
 * side answers "your prerequisite sealed as failed", and the controller
 * should stop waiting the moment it hears that, not poll to its own long
 * bound. This file is FAILURE ONLY. Nothing here can ever unblock a body
 * project — only a correctly signed `FREEZE_RELEASE_FILE` does — so a
 * controller that trusts this document can only ever fail earlier, never
 * proceed. A forged refusal therefore costs a run its barrier, which the
 * signing already guarantees; a missing one costs nothing.
 */
export const FREEZE_REFUSAL_FILE = 'freeze-refusal.json';

/**
 * Environment names the runner itself owns in every worker process, and
 * which the projection must therefore never touch.
 *
 * The reason is structural, read from the runner itself:
 * `worker/workerMain.js` assigns `TEST_WORKER_INDEX` and
 * `TEST_PARALLEL_INDEX` AFTER the process booted, and
 * `runner/workerHost.js` spreads `FORCE_COLOR` and `DEBUG_COLORS` into
 * every worker's environment at spawn. `lib/common/process.js` computes
 * the produced-environment diff against the worker's OWN boot
 * environment, so all four names appear in a produced diff without any
 * prerequisite having written them — a subtraction reset that touched
 * them would report a deletion the bodies then inherit.
 *
 * The reset set is otherwise derived BY SUBTRACTION — every key in the
 * controller's environment or in the trusted baseline, minus these four.
 * That is equivalent to a positively-owned namespace ONLY under the
 * invariant below, and the invariant is the real risk: nothing in the
 * run pins it, so a future change that starts injecting environment into
 * workers beyond these names would be silently projected away rather
 * than reported.
 *
 * Gateforge injects nothing into worker environment beyond the runner
 * child's own baseline: `buildRunnerChildEnv` refuses run-state paths
 * and signing material, and the freeze control reaches the controller
 * inlined in its generated spec rather than through the environment.
 * Under that invariant the worker's environment is the baseline, plus
 * preparation-written keys, plus these four names — so the reset set is
 * exactly the baseline keys a prerequisite overrode (restored) and the
 * keys a prerequisite introduced (deleted), whatever they are named.
 */
export const FREEZE_ENV_EXEMPT: readonly string[] = [
  'TEST_WORKER_INDEX',
  'TEST_PARALLEL_INDEX',
  'FORCE_COLOR',
  'DEBUG_COLORS',
];

/** One armed freeze barrier (paths, identities and the pinned spec bytes). */
export interface FreezeControl {
  /** Engine-owned controller project name. */
  project: string;
  /** The run identity (bound into request AND release). */
  runId: string;
  /** The invocation identity (bound into request AND release). */
  invocationId: string;
  /** Per-invocation random nonce; an old release can never match it. */
  nonce: string;
  /** Absolute path of this control's directory. */
  controlDir: string;
  /** Absolute path of the generated controller spec. */
  specPath: string;
  /** Absolute path of the request document. */
  requestPath: string;
  /** Absolute path of the release document. */
  releasePath: string;
  /** Absolute `<playwright>/test.js` the runner this run uses. */
  testModulePath: string;
  /** Absolute engine module the controller imports its primitives from. */
  barrierModulePath: string;
  /** Absolute path of the CLI's REFUSAL document (failure channel only). */
  refusalPath: string;
  /** Base64 raw SPKI Ed25519 PUBLIC key (the private key never leaves the CLI). */
  releasePublicKey: string;
  /** How long the controller waits for a valid release before failing. */
  timeoutMs: number;
  /**
   * The trusted runner MAIN/child environment BEFORE any project worker
   * ran — the exact baseline every body worker must be projected back to.
   * It is the child's OWN allowlisted environment, never the CLI's ambient
   * environment and never anything secret: the worker it describes already
   * runs with these very values.
   */
  baseEnv: Readonly<Record<string, string>>;
  /** Environment names the projection must never touch. */
  exemptEnv: readonly string[];
}

/** What the CLI hands the pack to arm one barrier. */
export interface FreezeArmInput {
  /** The run identity. */
  runId: string;
  /** The invocation identity. */
  invocationId: string;
  /** Per-invocation random nonce. */
  nonce: string;
  /** Absolute run-state dir (the barrier lives in its excluded subtree). */
  stateDir: string;
  /** Absolute `<playwright>/test.js` the supervised run will use. */
  testModulePath: string;
  /** Base64 raw SPKI Ed25519 public key for the release signature. */
  releasePublicKey: string;
  /** The trusted runner child's baseline environment. */
  baseEnv: Readonly<Record<string, string>>;
  /** How long the controller waits for a valid release. */
  timeoutMs: number;
}

/** The armed barrier plus the sha256 of the exact spec bytes written. */
export interface ArmedFreezeControl {
  control: FreezeControl;
  /** sha256 hex of the controller spec file the CLI pinned in memory. */
  specDigest: string;
}

/** The signed release payload (exactly what the signature covers). */
export interface FreezeReleasePayload {
  schemaVersion: 1;
  project: string;
  runId: string;
  invocationId: string;
  nonce: string;
  /** The prepared candidate tree the freeze produced. */
  preparedTreeId: string;
  /** sha256 of the controller spec bytes the CLI pinned before the run. */
  specDigest: string;
  /** ISO timestamp of the freeze (diagnostic; inside the signature). */
  sealedAt: string;
}

/** The signed release document the CLI writes and the controller reads. */
export interface FreezeReleaseDocument {
  schemaVersion: 1;
  payload: FreezeReleasePayload;
  /** Base64 Ed25519 signature over `canonicalFreezeJson(payload)`. */
  signature: string;
}

/** One controller request (written by the controller worker). */
export interface FreezeRequest {
  schemaVersion: 1;
  project: string;
  runId: string;
  invocationId: string;
  nonce: string;
  /** ISO timestamp the controller asked (diagnostic). */
  requestedAt: string;
}

/**
 * Deterministic canonical JSON: object keys sorted, no insignificant
 * whitespace. The CLI signs exactly these bytes and the controller
 * verifies exactly these bytes, so neither side may depend on a property
 * order or a serializer default.
 *
 * @param value: any JSON-compatible value.
 *
 * @returns
 *   string: the canonical form.
 */
export function canonicalFreezeJson(value: unknown): string {
  if (value === null || typeof value !== 'object') return JSON.stringify(value) ?? 'null';
  if (Array.isArray(value)) return `[${value.map((entry) => canonicalFreezeJson(entry)).join(',')}]`;
  const record = value as Record<string, unknown>;
  return `{${Object.keys(record)
    .sort()
    .map((key) => `${JSON.stringify(key)}:${canonicalFreezeJson(record[key])}`)
    .join(',')}}`;
}

/** One ephemeral per-invocation Ed25519 release-signing key pair. */
export interface FreezeSigningKeyPair {
  /** The public key object (verification only). */
  publicKey: KeyObject;
  /** The same public key as base64 raw SPKI, for the control data. */
  publicKeyBase64: string;
  /** The private key — CLI memory only, never a file or an environment. */
  privateKey: KeyObject;
}

/**
 * Mints one ephemeral Ed25519 key pair for the release signature. The
 * private key is returned to the CLI and NEVER written anywhere: not the
 * trusted config, not the run state, not a child environment.
 *
 * @returns
 *   FreezeSigningKeyPair: the pair, with the public key already
 *   base64-encoded as raw SPKI.
 */
export function mintFreezeSigningKeyPair(): FreezeSigningKeyPair {
  const pair = generateKeyPairSync('ed25519');
  const spki = pair.publicKey.export({ format: 'der', type: 'spki' });
  return {
    publicKey: pair.publicKey,
    publicKeyBase64: (spki as Buffer).toString('base64'),
    privateKey: pair.privateKey,
  };
}

/**
 * Signs one release payload with the invocation's ephemeral private key.
 *
 * @param privateKey: the ephemeral key (CLI memory only).
 * @param payload: the payload to sign.
 *
 * @returns
 *   FreezeReleaseDocument: the document the controller verifies.
 */
export function signFreezeRelease(privateKey: KeyObject, payload: FreezeReleasePayload): FreezeReleaseDocument {
  const signature = sign(null, Buffer.from(canonicalFreezeJson(payload), 'utf8'), privateKey);
  return { schemaVersion: 1, payload, signature: signature.toString('base64') };
}

/**
 * Verifies one release document against the pinned public key and the
 * exact identities the controller itself was armed with.
 *
 * A release passes only when ALL of these hold: the document shape, the
 * Ed25519 signature under the pinned key, the controller project name, the
 * run, the invocation, the per-invocation nonce, and the sha256 of the
 * controller's OWN current spec bytes. The last check is what makes a
 * replaced control file detectable rather than trusted.
 *
 * @param document: the parsed release document.
 * @param publicKeyBase64: the pinned base64 raw SPKI public key.
 * @param expected: the identities and spec digest the controller was armed with.
 *
 * @returns
 *   {ok: true, payload} | {ok: false, reason}: the verified payload, or the
 *   single plain reason the release was refused.
 */
export function verifyFreezeRelease(
  document: unknown,
  publicKeyBase64: string,
  expected: {
    project: string;
    runId: string;
    invocationId: string;
    nonce: string;
    specDigest: string;
  },
): { ok: true; payload: FreezeReleasePayload } | { ok: false; reason: string } {
  if (typeof document !== 'object' || document === null) {
    return { ok: false, reason: 'the freeze release is not an object' };
  }
  const row = document as Record<string, unknown>;
  if (row['schemaVersion'] !== 1 || typeof row['signature'] !== 'string') {
    return { ok: false, reason: 'the freeze release is missing its signature' };
  }
  const payload = row['payload'];
  if (typeof payload !== 'object' || payload === null) {
    return { ok: false, reason: 'the freeze release carries no payload' };
  }
  const fields = payload as Record<string, unknown>;
  if (fields['schemaVersion'] !== 1) {
    return { ok: false, reason: 'the freeze release payload has an unknown schema version' };
  }
  for (const key of ['project', 'runId', 'invocationId', 'nonce', 'preparedTreeId', 'specDigest', 'sealedAt'] as const) {
    if (typeof fields[key] !== 'string' || (fields[key] as string).length === 0) {
      return { ok: false, reason: `the freeze release payload has no ${key}` };
    }
  }
  let signatureOk = false;
  try {
    signatureOk = verify(
      null,
      Buffer.from(canonicalFreezeJson(fields), 'utf8'),
      createPublicKey({ key: Buffer.from(publicKeyBase64, 'base64'), format: 'der', type: 'spki' }),
      Buffer.from(row['signature'], 'base64'),
    );
  } catch {
    signatureOk = false;
  }
  if (!signatureOk) {
    return { ok: false, reason: 'the freeze release is unsigned or signed by another key' };
  }
  if (fields['project'] !== expected.project) {
    return { ok: false, reason: 'the freeze release names another controller project' };
  }
  if (fields['runId'] !== expected.runId || fields['invocationId'] !== expected.invocationId) {
    return { ok: false, reason: 'the freeze release belongs to another run or invocation' };
  }
  if (fields['nonce'] !== expected.nonce) {
    return { ok: false, reason: 'the freeze release was minted for another nonce (a replayed release)' };
  }
  if (fields['specDigest'] !== expected.specDigest) {
    return { ok: false, reason: 'the controller control spec no longer matches the bytes the run pinned' };
  }
  return { ok: true, payload: fields as unknown as FreezeReleasePayload };
}

/**
 * Projects one worker environment back to the trusted baseline the runner
 * child started with.
 *
 * The native scheduler unions every dependency worker's produced
 * environment into its dependents, so a body worker inherits whatever a
 * prerequisite worker assigned — including a deleted key, which the
 * scheduler carries as `undefined` and Node then simply omits from the
 * child. This restores exactly that difference: every key whose current
 * value differs from the baseline goes back to the baseline value, or is
 * deleted when the baseline never had it. The keys Playwright's own
 * worker bootstrap writes ({@link FREEZE_ENV_EXEMPT}) are left alone —
 * they are the runner's, not a prerequisite's.
 *
 * @param current: the controller worker's own environment (mutated in place).
 * @param base: the trusted runner child's baseline environment.
 * @param exempt: names the projection must not touch.
 *
 * @returns
 *   {restored: string[], deleted: string[]}: what the projection changed,
 *   sorted, for the controller's own diagnostic.
 */
export function projectBaselineEnv(
  current: Record<string, string | undefined>,
  base: Readonly<Record<string, string>>,
  exempt: readonly string[] = FREEZE_ENV_EXEMPT,
): { restored: string[]; deleted: string[] } {
  const skip = new Set(exempt);
  const restored: string[] = [];
  const deleted: string[] = [];
  for (const key of [...new Set([...Object.keys(current), ...Object.keys(base)])].sort()) {
    if (skip.has(key)) continue;
    const want = base[key];
    if (want === undefined) {
      if (Object.prototype.hasOwnProperty.call(current, key) && current[key] !== undefined) {
        delete current[key];
        deleted.push(key);
      }
      continue;
    }
    if (current[key] !== want) {
      current[key] = want;
      restored.push(key);
    }
  }
  return { restored, deleted };
}

/**
 * Resolves the engine barrier module the generated controller imports.
 * Absolute and pack-relative for the same reason the trusted reporter
 * entry is: a generated worker spec must load an ENGINE file by absolute
 * path, never a candidate-relative one. Resolves from both the `src/` and
 * the `dist/` layout.
 *
 * @param fromModule: module URL to resolve the pack from (default: this file).
 *
 * @returns
 *   string: absolute `<pack>/dist|src/discovery/prepare-barrier.js` path.
 */
export function barrierModulePath(fromModule: string = import.meta.url): string {
  return fileURLToPath(new URL('./prepare-barrier.js', fromModule));
}

/**
 * The controller worker's own bytes.
 *
 * The generated spec imports the ENGINE barrier module by absolute path so
 * the canonical payload form, the signature verification and the
 * environment projection are ONE implementation on both sides — never a
 * second copy that can drift from the one the CLI signed.
 *
 * @param control: the armed control (paths and pinned identities).
 *
 * @returns
 *   string: the generated TypeScript source of the controller spec.
 */
export function freezeControllerSpecSource(control: FreezeControl): string {
  const armed = {
    project: control.project,
    runId: control.runId,
    invocationId: control.invocationId,
    nonce: control.nonce,
    requestPath: control.requestPath,
    refusalPath: control.refusalPath,
    releasePath: control.releasePath,
    specPath: control.specPath,
    releasePublicKey: control.releasePublicKey,
    timeoutMs: control.timeoutMs,
    baseEnv: control.baseEnv,
    exemptEnv: control.exemptEnv,
  };
  return `// GENERATED by gateforge trusted supervision — the GLOBAL native
// preparation freeze controller. Never edit: the CLI pinned these exact
// bytes before the run and the signed release binds their sha256.
import { existsSync, readFileSync, writeFileSync } from 'node:fs';
import { createHash } from 'node:crypto';
import { test, expect } from ${JSON.stringify(control.testModulePath)};
import {
  canonicalFreezeJson,
  projectBaselineEnv,
  verifyFreezeRelease,
} from ${JSON.stringify(control.barrierModulePath)};

const ARMED = ${JSON.stringify(armed, null, 2)};

test('gateforge global preparation freeze', async () => {
  test.setTimeout(ARMED.timeoutMs + 60000);
  writeFileSync(
    ARMED.requestPath,
    canonicalFreezeJson({
      schemaVersion: 1,
      project: ARMED.project,
      runId: ARMED.runId,
      invocationId: ARMED.invocationId,
      nonce: ARMED.nonce,
      requestedAt: new Date().toISOString(),
    }) + '\\n',
    'utf8',
  );
  // Wait for EITHER outcome. A refusal is failure-only: it can end this
  // wait early but never unblock it, so a permanent refusal (a
  // prerequisite that sealed failed, skipped, retried or duplicated)
  // fails the controller within the poll interval instead of running out
  // the whole bound. A forged refusal costs the run its barrier, which
  // the signed release already guarantees; a missing one costs nothing.
  await expect
    .poll(
      () => (existsSync(ARMED.releasePath) ? 'released' : existsSync(ARMED.refusalPath) ? 'refused' : 'waiting'),
      { timeout: ARMED.timeoutMs, intervals: [25] },
    )
    .not.toBe('waiting');
  // A release document that EXISTS is always read and verified, even when
  // a refusal document sits beside it. The signature is the only thing
  // that can unblock a body, so a present release must produce its OWN
  // verdict — an unsigned document, one signed by another key and a
  // replayed document from an earlier invocation each have a distinct,
  // precise reason, and consulting the refusal first would mask all three
  // behind the refusal's wording. The refusal is read only when there is
  // no release at all, which is the ordinary refusal path.
  if (existsSync(ARMED.releasePath)) {
    let release: unknown = null;
    try {
      release = JSON.parse(readFileSync(ARMED.releasePath, 'utf8'));
    } catch (error) {
      expect(false, 'the freeze release is not readable JSON: ' + String(error)).toBe(true);
    }
    const verified = verifyFreezeRelease(release, ARMED.releasePublicKey, {
      project: ARMED.project,
      runId: ARMED.runId,
      invocationId: ARMED.invocationId,
      nonce: ARMED.nonce,
      specDigest: createHash('sha256').update(readFileSync(ARMED.specPath)).digest('hex'),
    });
    expect(verified.ok, verified.ok ? '' : verified.reason).toBe(true);
  } else {
    const refusal = JSON.parse(readFileSync(ARMED.refusalPath, 'utf8')) as { reason?: unknown };
    throw new Error(
      'the trusted side refused the prepared candidate: ' +
        (typeof refusal.reason === 'string' ? refusal.reason : 'no reason given'),
    );
  }
  // The environment projection is the whole reason this worker exists:
  // the native scheduler unions every dependency worker's produced
  // environment into its dependents, so a prerequisite's assignment
  // would otherwise reach every body. Assert the RESULT, not that the
  // projection ran — after it, every non-exempt name must carry exactly
  // the baseline value and nothing the baseline never had may remain.
  projectBaselineEnv(process.env, ARMED.baseEnv, ARMED.exemptEnv);
  const exempt = new Set(ARMED.exemptEnv);
  const drifted = [...new Set([...Object.keys(process.env), ...Object.keys(ARMED.baseEnv)])]
    .filter((key) => !exempt.has(key))
    .filter((key) => (process.env[key] ?? null) !== (ARMED.baseEnv[key] ?? null))
    .sort();
  expect(drifted, 'the worker environment still differs from the trusted baseline: ' + drifted.join(', ')).toEqual([]);
});
`;
}

/**
 * Writes the controller spec and returns the armed barrier plus the sha256
 * of the exact bytes written. The spec is GENERATED engine code in the
 * excluded run-state subtree: it is the only worker that performs the
 * handshake, and its bytes are pinned in CLI memory for the whole run.
 *
 * @param input: the identities, paths, public key and baseline environment.
 *
 * @returns
 *   ArmedFreezeControl: the control (with absolute paths) and its spec digest.
 */
export function armFreezeControl(input: FreezeArmInput): ArmedFreezeControl {
  const controlDir = join(input.stateDir, FREEZE_CONTROL_DIR);
  mkdirSync(controlDir, { recursive: true, mode: 0o700 });
  // Owner-only. The control directory holds the pinned public key, the
  // controller's request, the CLI's signed release and the refusal
  // document; nothing else on this host has a reason to read them, and
  // the default 0o755/0o644 would publish the baseline allowlisted
  // variables the generated spec embeds. The private signing key is
  // NEVER written here — it stays in the CLI process's memory.
  chmodSync(controlDir, 0o700);
  const control: FreezeControl = {
    project: FREEZE_CONTROLLER_PROJECT,
    runId: input.runId,
    invocationId: input.invocationId,
    nonce: input.nonce,
    controlDir,
    specPath: join(controlDir, FREEZE_CONTROL_SPEC_FILE),
    requestPath: join(controlDir, FREEZE_REQUEST_FILE),
    releasePath: join(controlDir, FREEZE_RELEASE_FILE),
    refusalPath: join(controlDir, FREEZE_REFUSAL_FILE),
    testModulePath: input.testModulePath,
    barrierModulePath: barrierModulePath(),
    releasePublicKey: input.releasePublicKey,
    timeoutMs: input.timeoutMs,
    baseEnv: { ...input.baseEnv },
    exemptEnv: [...FREEZE_ENV_EXEMPT],
  };
  // A previous invocation's handshake must not be visible to this one: a
  // stale request would be served before this run's controller ever asks,
  // and a stale release or refusal would be read by a controller that
  // never asked. Only the SPEC survives, and it is rewritten below.
  for (const path of [control.requestPath, control.releasePath, control.refusalPath]) {
    rmSync(path, { force: true });
  }
  const source = freezeControllerSpecSource(control);
  writeFileSync(control.specPath, source, { encoding: 'utf8', mode: 0o600 });
  return {
    control,
    specDigest: createHash('sha256').update(source).digest('hex'),
  };
}

/**
 * Writes the trusted side's REFUSAL document for one handshake. It is
 * failure-only by construction: no code path in the controller treats
 * its presence as permission to continue, so a refusal can only shorten a
 * wait, never satisfy one.
 *
 * @param control: the armed control.
 * @param reason: the plain refusal text the controller surfaces.
 */
export function writeFreezeRefusal(control: FreezeControl, reason: string): void {
  writeFileSync(
    control.refusalPath,
    `${canonicalFreezeJson({
      schemaVersion: 1,
      project: control.project,
      runId: control.runId,
      invocationId: control.invocationId,
      nonce: control.nonce,
      reason,
    })}\n`,
    { encoding: 'utf8', mode: 0o600 },
  );
}

/**
 * Reads the controller's request document, or null when it is absent or
 * unusable. An absent request is ordinary (the controller has not asked
 * yet); a MALFORMED one is a refusal the trusted side reports.
 *
 * @param path: absolute request document path.
 *
 * @returns
 *   FreezeRequest | null: the parsed request, or null.
 */
export function readFreezeRequest(path: string): FreezeRequest | null {
  let raw: string;
  try {
    raw = readFileSync(path, 'utf8');
  } catch {
    return null;
  }
  let parsed: unknown;
  try {
    parsed = JSON.parse(raw);
  } catch {
    return null;
  }
  if (typeof parsed !== 'object' || parsed === null) return null;
  const row = parsed as Record<string, unknown>;
  if (row['schemaVersion'] !== 1) return null;
  for (const key of ['project', 'runId', 'invocationId', 'nonce'] as const) {
    if (typeof row[key] !== 'string' || (row[key] as string).length === 0) return null;
  }
  return {
    schemaVersion: 1,
    project: row['project'],
    runId: row['runId'],
    invocationId: row['invocationId'],
    nonce: row['nonce'],
    requestedAt: typeof row['requestedAt'] === 'string' ? row['requestedAt'] : '',
  };
}

/**
 * Rewrites the planned project scopes into the freeze-aware shape the
 * synthesized config emits.
 *
 * The rules, in the order they matter:
 *
 * - The engine's controller project is appended as one more scope. It
 *   collects its generated spec from its OWN `testDir` (the excluded
 *   run-state subtree) and depends on the FULL upstream prerequisite
 *   closure the trusted CLI classified — so the runner's own scheduler
 *   runs every prerequisite, then the controller, then any body.
 * - A PREREQUISITE keeps its captured edges exactly as they were. Its
 *   rows are the native cases that must execute genuinely and exactly
 *   once, and re-ordering them would change what the run proves.
 * - Every other project gets the controller as its FIRST dependency,
 *   followed by its own captured edges in their original emitted order.
 *   Placement is not an ordering statement — the runner's phase scheduler
 *   is topological (`runner/tasks.js`: a project joins the earliest phase
 *   in which every dependency is already processed), so a body runs after
 *   the controller either way. Placement IS an environment-merge
 *   statement: a project's extra environment is the union over
 *   `project.deps` in emitted order (`tasks.js:341-347`), later entries
 *   winning, so where the controller lands decides what a body starts
 *   with. FIRST is the contract's placement, emitted explicitly rather
 *   than by inserting into a sorted array (a sort would move the
 *   controller behind any prerequisite that sorts before it);
 *   `trusted-config.ts` re-asserts it when it emits the final list. Whether
 *   FIRST or LAST is what the environment projection actually needs is
 *   under live measurement by the native environment probe; this is the
 *   contract's ordering until that measurement says otherwise.
 * @param control: the armed controller (its project name, dir and spec).
 * @param scopes: the planned project scopes, unchanged in every other way.
 * @param prerequisiteProjects: the CLI's upstream-closure classification.
 *
 * @returns
 *   ProjectScope[]: the scopes to synthesize — the planned scopes in
 *   place, plus the controller appended.
 */
export function freezeProjectScopes(
  control: FreezeControl,
  scopes: readonly ProjectScope[],
  prerequisiteProjects: readonly string[],
): ProjectScope[] {
  const defined = new Set(scopes.map((scope) => scope.name));
  const prerequisites = new Set(
    prerequisiteProjects.filter((name) => defined.has(name) && name !== control.project),
  );
  return [
    ...scopes.map((scope) =>
      prerequisites.has(scope.name) || scope.name === control.project
        ? scope
        : {
            ...scope,
            dependencies: [
              control.project,
              ...(scope.dependencies ?? []).filter((name) => name !== control.project),
            ],
          },
    ),
    {
      name: control.project,
      files: [FREEZE_CONTROL_SPEC_FILE],
      testDir: control.controlDir,
      dependencies: [...prerequisites].sort(),
    },
  ];
}
