/**
 * `gateforge enforcement doctor` reads a framework-managed commit hook
 * as WIRED, not as a foreign hook (0.9.0, problem 8).
 *
 * A pre-commit framework regenerates `.git/hooks/pre-commit` from
 * `.pre-commit-config.yaml` on every install, so that file carries the
 * framework's signature and never a Gateforge marker. The doctor used to
 * report exactly that as "a non-gateforge pre-commit hook exists … gateforge
 * did not touch it" — on the same repository where `init` had just said
 * "framework-managed pre-commit hook detected: wiring through
 * .pre-commit-config.yaml".
 *
 * Both halves must hold before the gate counts as wired: the hook file is
 * framework generated AND the framework config really declares our hook.
 * The negative cases below pin that — a framework hook without our entry
 * is still a warn, not an all-clear.
 */
import { mkdirSync, writeFileSync } from 'node:fs';
import { join } from 'node:path';
import { describe, expect, it } from 'vitest';
import { withTempRepo, type TempRepo } from '@gate-forge/core';
import { installFixture, runCli } from './helpers.js';

/** A `.pre-commit-config.yaml` that declares Gateforge's hook. */
const PRE_COMMIT_CONFIG = `repos:
  - repo: local
    hooks:
      - id: gateforge-check
        name: gateforge — unresolved findings / unwaived obligations
        entry: node .gateforge/hooks/gateforge-check.mjs
        language: system
        pass_filenames: false
`;

/** A framework-managed `.git/hooks/pre-commit` (never carries our marker). */
const FRAMEWORK_HOOK = `#!/usr/bin/env bash
# File generated by pre-commit
ARGS=(hook-impl --config=.pre-commit-config.yaml --hook-type=pre-commit)
HERE="$(cd "$(dirname "$0")" && pwd)"
ARGS+=(--hook-dir "$HERE" --)
exec "pre-commit" hook-impl --config=.pre-commit-config.yaml --hook-type=pre-commit
`;

interface DoctorJson {
  level: number;
  checks: Array<{ id: string; status: string; detail: string }>;
}

/** The doctor's `hook` check plus the reported enforcement level. */
async function hookCheck(repo: TempRepo): Promise<{ status: string; detail: string; level: number }> {
  const { code, stdout, stderr } = await runCli(repo, ['enforcement', 'doctor', '--json']);
  expect(code, `${stdout}\n${stderr}`).toBe(0);
  const report = JSON.parse(stdout) as DoctorJson;
  const hook = report.checks.find((entry) => entry.id === 'hook');
  expect(hook, "the doctor always reports a 'hook' check").toBeTruthy();
  const found = hook as { status: string; detail: string };
  return { status: found.status, detail: found.detail, level: report.level };
}

/** A repository whose commit hook is framework-generated, plus a config. */
async function withFrameworkHook(
  config: string,
  run: (check: () => Promise<{ status: string; detail: string; level: number }>) => Promise<void>,
): Promise<void> {
  await withTempRepo({}, async (repo) => {
    installFixture(repo);
    mkdirSync(join(repo.root, '.git', 'hooks'), { recursive: true });
    writeFileSync(join(repo.root, '.git', 'hooks', 'pre-commit'), FRAMEWORK_HOOK, { mode: 0o755 });
    if (config !== '') repo.writeFiles({ '.pre-commit-config.yaml': config });
    await run(async () => hookCheck(repo));
  });
}

describe('enforcement doctor understands a framework-managed commit hook (8)', () => {
  it('reports ok when the framework config declares gateforge-check', async () => {
    await withFrameworkHook(PRE_COMMIT_CONFIG, async (check) => {
      const hook = await check();
      expect(hook.status).toBe('ok');
      expect(hook.detail).toContain('pre-commit framework');
      expect(hook.detail).toContain('gateforge-check');
      expect(hook.detail).not.toContain('non-gateforge');
      // An active local hook is level 1, exactly like a Gateforge-owned one.
      expect(hook.level).toBeGreaterThanOrEqual(1);
    });
  });

  it('still warns when the framework config does NOT declare gateforge-check', async () => {
    const foreignOnly = `repos:
  - repo: local
    hooks:
      - id: some-other-check
        name: the repository's own check
        entry: node scripts/check.mjs
        language: system
        pass_filenames: false
`;
    await withFrameworkHook(foreignOnly, async (check) => {
      const hook = await check();
      expect(hook.status).toBe('warn');
      expect(hook.detail).toContain('non-gateforge');
    });
  });

  it('still warns when there is no framework config at all', async () => {
    await withFrameworkHook('', async (check) => {
      const hook = await check();
      expect(hook.status).toBe('warn');
      expect(hook.detail).toContain('non-gateforge');
    });
  });

  it('reports the commit gate NOT active (fail) when the config declares gateforge-check but no hook exists yet', async () => {
    // R1-7: `.pre-commit-config.yaml` declares our hook, but the
    // framework has not installed its generated hook file yet —
    // until `pre-commit install` runs, the commit gate is NOT
    // active, so the row must fail (never an ok all-clear).
    await withTempRepo({}, async (repo) => {
      installFixture(repo);
      repo.writeFiles({ '.pre-commit-config.yaml': PRE_COMMIT_CONFIG });
      const { code, stdout, stderr } = await runCli(repo, ['enforcement', 'doctor', '--json']);
      expect(code, `${stdout}\n${stderr}`).toBe(0);
      const report = JSON.parse(stdout) as DoctorJson;
      const hook = report.checks.find((entry) => entry.id === 'hook');
      expect(hook, "the doctor always reports a 'hook' check").toBeTruthy();
      const found = hook as { status: string; detail: string };
      expect(found.status).toBe('fail');
      expect(found.detail).toContain('NOT active');
      expect(found.detail).toContain('pre-commit install');
      // The text surface carries the same action.
      const text = await runCli(repo, ['enforcement', 'doctor']);
      expect(text.code).toBe(0);
      expect(text.stdout).toContain('pre-commit install');
    });
  });
});
