/**
 * The engine's OWN generated run state is never a declared input.
 * Reproduced on a real third-party repository, after its first supervised
 * run: the run writes its synthesized runner config into the state
 * directory (`--out`, default `.gateforge/test-gates/`), and because
 * `gateforge init` declares every `.mjs`, `.js`, `.ts` and `.py` file as
 * a scan glob (the default `paths.include` set), so the NEXT commands —
 * `gateforge check`, then `gateforge next`, the documented step 8 —
 *
 *   refusing to run: --out '<repo>/.gateforge/test-gates' overlaps
 *   declared source/configuration inputs
 *   (.gateforge/test-gates/trusted.playwright.config.mjs); generated run
 *   state must not hide tested inputs from the digest
 *
 * i.e. the gate became permanently unrunnable in that repository until a
 * user deleted the file by hand. The refusal itself is right and stays:
 * it protects the digest from a tested input hiding inside run state. What
 * was wrong is that the engine's own output was treated as a suspect.
 *
 * Pinned here:
 *   - the generated files the engine writes into the state directory do
 *     NOT make the run refuse — with a repository at `init`'s defaults,
 *     `check` runs to a verdict once the supervised run has written its
 *     trusted config there;
 *   - a TRACKED file in the state directory still refuses (exit 2), and so
 *     does any file there the engine did not generate: the hole stays
 *     closed, fail-closed and byte-identical in its wording;
 *   - the declared-input list keeps every other entry untouched, so the
 *     digest of a repository whose state directory holds only generated
 *     files is unchanged.
 */
import { describe, expect, it } from 'vitest';
import { join } from 'node:path';
import { readFileSync, writeFileSync } from 'node:fs';
import { withTempRepo } from '@gate-forge/core';
import { assertOutputDisjoint } from '../src/input-snapshot.js';
import { resolveStateDir } from '../src/state.js';
import { installFixture, runCli } from './helpers.js';

/** The trusted runner config the supervised Playwright run synthesizes. */
const TRUSTED_CONFIG = '// generated by gateforge\nexport default {};\n';

/** A file no engine run ever writes. */
const FOREIGN_FILE = 'notes = 1\n';

describe('the engine generated run state is not a declared input', () => {
  it('runs the gate at init defaults once the supervised run wrote its trusted config', async () => {
    await withTempRepo({}, async (repo) => {
      repo.writeFiles({
        'app/main.js': 'export const app = 1;\n',
        'app/service.ts': 'export const service = 1;\n',
      });
      const initialized = await runCli(repo, ['init']);
      expect(initialized.code, `${initialized.stdout}\n${initialized.stderr}`).toBe(0);
      const config = readFileSync(join(repo.root, '.gateforge.yml'), 'utf8');
      expect(config).toContain("'**/*.mjs'");
      repo.writeFiles({ 'app/handler.js': 'export const handler = 1;\n' });
      repo.stage();
      repo.commit('app sources');

      // The run's own output, exactly where the supervised run puts it.
      repo.writeFiles({
        '.gateforge/test-gates/trusted.playwright.config.mjs': TRUSTED_CONFIG,
        '.gateforge/test-gates/manifest.json': '{"schemaVersion":1}\n',
      });
      const check = await runCli(repo, ['check']);
      expect(check.code).not.toBe(2);
      expect(`${check.stdout}\n${check.stderr}`).not.toContain('overlaps declared source');
      // …and the command the block was printed by agrees.
      const next = await runCli(repo, ['next']);
      expect(next.code).not.toBe(2);
      expect(`${next.stdout}\n${next.stderr}`).not.toContain('overlaps declared source');
    });
  });

  it('still refuses a tracked file inside the state directory', async () => {
    await withTempRepo({}, async (repo) => {
      installFixture(repo);
      repo.stage();
      repo.commit('fixture');
      repo.writeFiles({ '.gateforge/test-gates/committed.py': FOREIGN_FILE });
      // The fixture gitignores the state directory, so the file is
      // committed explicitly — a repository that tracks its own run
      // state is exactly the unsafe case the refusal exists for.
      repo.git(['add', '--force', '.gateforge/test-gates/committed.py']);
      repo.commit('a committed file inside the state directory');
      const check = await runCli(repo, ['check']);
      expect(check.code).toBe(2);
      expect(check.stderr).toContain('overlaps committed source');
    });
  });

  it('still refuses an untracked file the engine did not generate', async () => {
    await withTempRepo({}, async (repo) => {
      installFixture(repo, { include: "['**/*.py']" });
      repo.stage();
      repo.commit('fixture');
      repo.writeFiles({ '.gateforge/test-gates/hand-written.py': FOREIGN_FILE });
      const check = await runCli(repo, ['check']);
      expect(check.code).toBe(2);
      expect(check.stderr).toContain('overlaps declared source');
      expect(check.stderr).toContain('hand-written.py');
    });
  });

  it('keeps every other declared input in the overlap test', async () => {
    await withTempRepo({}, async (repo) => {
      installFixture(repo);
    const stateDir = resolveStateDir(repo.root);
    // Generated run state: no refusal…
    expect(() =>
      assertOutputDisjoint(repo.root, stateDir, [
        'src/accounts.txt',
        '.gateforge/test-gates/trusted.playwright.config.mjs',
        '.gateforge/test-gates/manifest.json',
        '.gateforge/test-gates/report.json',
      ]),
    ).not.toThrow();
    // …a file the engine did not generate: still refused, same wording.
    expect(() =>
      assertOutputDisjoint(repo.root, stateDir, [
        'src/accounts.txt',
        '.gateforge/test-gates/hand-written.py',
      ]),
    ).toThrow(
      /overlaps declared source\/configuration inputs \(\.gateforge\/test-gates\/hand-written\.py\)/,
    );
    });
  });
});
