/**
 * The engine's OWN generated run state is an output, never a declared
 * input — and the boundary that says so is the ACTUAL state directory
 * plus a closed list of the names the engine writes there.
 *
 * Reproduced on a real third-party repository, after its first supervised
 * run: the run writes its synthesized runner config and its generated
 * preparation-freeze controller into the state directory (`--out`,
 * default `.gateforge/test-gates/`), and because `gateforge init`
 * declares every `.mjs`/`.js`/`.cjs` file as a scan glob, the NEXT
 * commands — `gateforge check`, then `gateforge next`, the documented
 * step 8 — either refused to run, or inventoried the engine's own
 * controller as a test the owner never wrote:
 *
 *   refusing to run: --out '<repo>/.gateforge/test-gates' overlaps
 *   declared source/configuration inputs
 *   (.gateforge/test-gates/trusted.playwright.config.mjs); generated run
 *   state must not hide tested inputs from the digest
 *
 * The refusal itself is right and stays: it protects the digest from a
 * tested input hiding inside run state. What was wrong is that the
 * engine's own output was treated as a suspect.
 *
 * Pinned here, through the real CLI and nothing else:
 *   - the generated files the engine writes into the state directory do
 *     NOT make the gate refuse, and they are NOT inventoried as tests;
 *   - the exclusion is a property of the resolved state directory and of
 *     the engine's own file names, so a file that merely SHARES one of
 *     those names outside that directory stays a visible test — including
 *     one in a sibling directory whose name merely BEGINS with the state
 *     directory's — while a hand-written file inside the state directory
 *     stays visible and still refuses the run;
 *   - a custom `--out` state directory is judged by ITSELF, never by the
 *     default directory's assumptions;
 *   - a TRACKED file in the state directory still refuses, including when
 *     it carries one of the engine's own generated names.
 */
import { existsSync } from 'node:fs';
import { describe, expect, it } from 'vitest';
import { withTempRepo } from '@gate-forge/core';
import { installFixture, runCli } from './helpers.js';

/** The trusted runner config the supervised Playwright run synthesizes. */
const TRUSTED_CONFIG = '// generated by gateforge\nexport default {};\n';

/** A file no engine run ever writes. */
const FOREIGN_FILE = 'notes = 1\n';

/** A real, statically discoverable test file with the given title. */
function specFile(title: string): string {
  return `import { test } from 'playwright/test';

test('${title}', async ({ page }) => {
  await page.goto('/accounts');
});
`;
}

/**
 * Every file `gateforge tests catalog --json` inventoried.
 *
 * @param stdout: the command's stdout.
 *
 * @returns
 *   string[]: the repo-relative file of each catalog entry, in catalog order.
 */
function catalogFiles(stdout: string): string[] {
  const document = JSON.parse(stdout) as { entries: Array<{ file: string }> };
  return document.entries.map((entry) => entry.file);
}

describe('the engine generated run state is not a declared input', () => {
  it('runs the gate at init defaults once the supervised run wrote its generated state', async () => {
    await withTempRepo({}, async (repo) => {
      repo.writeFiles({
        'app/main.js': 'export const app = 1;\n',
        'app/service.ts': 'export const service = 1;\n',
      });
      const initialized = await runCli(repo, ['init']);
      expect(initialized.code, `${initialized.stdout}\n${initialized.stderr}`).toBe(0);
      repo.writeFiles({ 'app/handler.js': 'export const handler = 1;\n' });
      repo.stage();
      repo.commit('app sources');

      // The run's own output, exactly where the supervised run puts it.
      repo.writeFiles({
        '.gateforge/test-gates/trusted.playwright.config.mjs': TRUSTED_CONFIG,
        '.gateforge/test-gates/manifest.json': '{"schemaVersion":1}\n',
      });
      const check = await runCli(repo, ['check', '--format', 'json']);
      // A verdict (0) or a gate outcome (1) — never the usage refusal (2)
      // that the documented step 8 command used to produce here.
      expect([0, 1]).toContain(check.code);
      // …and the command the block was printed by agrees.
      const next = await runCli(repo, ['next', '--json']);
      expect([0, 1]).toContain(next.code);
    });
  });

  it('never inventories a generated state file as a test, and never hides a lookalike', async () => {
    await withTempRepo({}, async (repo) => {
      // A consumer at `init`'s declared globs: every parseable file is in
      // scan scope. Its run-state directory is NOT gitignored, which is
      // the ordinary shape of a real repository — so nothing but the
      // engine's own ownership registry can keep its output out of the
      // inventory.
      installFixture(repo, { include: "['**/*.mjs']" });
      repo.writeFiles({ '.gitignore': 'node_modules\n' });
      repo.stage();
      repo.commit('consumer project');
      repo.writeFiles({
        // The engine's OWN generated output at the path and name the
        // preparation freeze really writes.
        '.gateforge/test-gates/native-freeze/freeze-controller.spec.mjs': specFile('gateforge global preparation freeze'),
        // A hand-written file inside the state directory that the engine
        // never generates and never claims.
        '.gateforge/test-gates/hand-written.spec.mjs': specFile('a state directory file the engine never wrote'),
        // The SAME generated name and title, outside the state directory.
        'specs/native-freeze/freeze-controller.spec.mjs': specFile('gateforge global preparation freeze'),
        // A SIBLING directory whose name merely starts with the state
        // directory's: the ownership boundary is the directory itself,
        // never a prefix of its path.
        '.gateforge/test-gates-extra/native-freeze/freeze-controller.spec.mjs': specFile('gateforge global preparation freeze'),
      });

      const catalog = await runCli(repo, ['tests', 'catalog', '--json']);
      expect(catalog.code, `${catalog.stdout}\n${catalog.stderr}`).toBe(0);
      const files = catalogFiles(catalog.stdout);
      // The generated controller is the engine's output: no catalog row.
      expect(files).not.toContain('.gateforge/test-gates/native-freeze/freeze-controller.spec.mjs');
      // An unknown file in the state directory is NOT hidden from the
      // inventory either — it is refused below, not silently dropped.
      expect(files).toContain('.gateforge/test-gates/hand-written.spec.mjs');
      // A file outside the state directory stays a candidate whatever it
      // is named: the boundary is the directory, never the title.
      expect(files).toContain('specs/native-freeze/freeze-controller.spec.mjs');
      // …and so does a sibling directory whose name merely BEGINS with the
      // state directory's: ownership is the directory, not its prefix.
      expect(files).toContain('.gateforge/test-gates-extra/native-freeze/freeze-controller.spec.mjs');
    });
  });

  it('still refuses an untracked file the engine never generated', async () => {
    await withTempRepo({}, async (repo) => {
      installFixture(repo, { include: "['**/*.py']" });
      repo.stage();
      repo.commit('fixture');
      repo.writeFiles({ '.gateforge/test-gates/hand-written.py': FOREIGN_FILE });
      const check = await runCli(repo, ['check']);
      expect(check.code).toBe(2);
    });
  });

  it('still refuses a tracked file carrying one of the engine own generated names', async () => {
    await withTempRepo({}, async (repo) => {
      // The glob really covers that generated `.mjs` as a declared input,
      // so only the TRACKED-source rule can be what refuses here: the file
      // carries exactly the name the engine's own output has.
      installFixture(repo, { include: "['**/*.mjs']" });
      repo.stage();
      repo.commit('fixture');
      repo.writeFiles({ '.gateforge/test-gates/trusted.playwright.config.mjs': TRUSTED_CONFIG });
      // The fixture gitignores the state directory, so the file is
      // committed explicitly — a repository that tracks its own run state
      // is exactly the unsafe case the refusal exists for, and the
      // generated NAME does not make those bytes safe to hide.
      repo.git(['add', '--force', '.gateforge/test-gates/trusted.playwright.config.mjs']);
      repo.commit('a committed generated file inside the state directory');
      const check = await runCli(repo, ['check']);
      expect(check.code).toBe(2);
    });
  });

  it('judges a custom out state directory by itself, never by the default one', async () => {
    await withTempRepo({}, async (repo) => {
      installFixture(repo, { include: "['**/*.mjs', '**/*.py']" });
      repo.stage();
      repo.commit('fixture');
      const custom = 'custom-state';
      repo.writeFiles({ [`${custom}/trusted.playwright.config.mjs`]: TRUSTED_CONFIG });

      // The engine's own output inside the state directory this run
      // actually resolved: no refusal, and the default directory is never
      // consulted or created.
      const generated = await runCli(repo, ['test-gates', '--suite', 'true', '--out', custom, '--format', 'json']);
      // A verdict (0) or a gate outcome (1) — never the usage refusal (2),
      // and never the default state directory, which this run never created.
      expect([0, 1]).toContain(generated.code);
      expect(existsSync(repo.path('.gateforge/test-gates'))).toBe(false);

      // A hand-written file in that SAME directory still refuses, so the
      // exemption is a statement about what the engine writes and not
      // about where the run happened to put its state.
      repo.writeFiles({ [`${custom}/hand-written.py`]: FOREIGN_FILE });
      const refused = await runCli(repo, ['test-gates', '--suite', 'true', '--out', custom, '--format', 'json']);
      expect(refused.code).toBe(2);
    });
  });
});