/**
 * `gateforge init`: generation, idempotence, and the no-overwrite rule
 * (automatic classification contract).
 */
import { mkdirSync, writeFileSync, readFileSync, existsSync } from 'node:fs';
import { join } from 'node:path';
import { describe, expect, it } from 'vitest';
import { parse as parseYaml } from 'yaml';
import { withTempRepo, loadConfig } from '@gate-forge/core';
import { runCli } from './helpers.js';

const TARGETS = [
  '.gateforge.yml',
  '.gateforge/policies.yml',
  '.gateforge/classification-policy.yml',
  '.gateforge/baselines/obligations.json',
];

describe('gateforge init', () => {
  it('generates the config, documents, and skeleton dirs', async () => {
    await withTempRepo({}, async (repo) => {
      const { code, stdout } = await runCli(repo, ['init']);
      expect(code).toBe(0);
      for (const target of TARGETS) {
        expect(existsSync(repo.path(target)), `${target} exists`).toBe(true);
        expect(stdout).toContain(`created: ${repo.path(target)}`);
      }
      expect(existsSync(repo.path('.gateforge/adapters'))).toBe(true);
      expect(existsSync(repo.path('.gateforge/waivers'))).toBe(true);
      // The generated config must be loadable by the pinned schema.
      expect(() => loadConfig(join(repo.root, '.gateforge.yml'))).not.toThrow();
    });
  });

  it('--blocking integrates through a framework-managed pre-commit hook without manual chaining', async () => {
    await withTempRepo({}, async (repo) => {
      // A pre-commit-FRAMEWORK-generated .git hook: regenerated from
      // .pre-commit-config.yaml on every install — gateforge must wire
      // through the framework config, never demand chaining into it.
      const hooksDir = repo.path('.git/hooks');
      mkdirSync(hooksDir, { recursive: true });
      writeFileSync(join(hooksDir, 'pre-commit'), [
        '#!/usr/bin/env bash',
        '# File generated by pre-commit: https://pre-commit.com',
        '# start templated',
        'ARGS=(hook-impl --config=.pre-commit-config.yaml --hook-type=pre-commit)',
        '# end templated',
        'exec "$INSTALL_PYTHON" -mpre_commit "${ARGS[@]}"',
        '',
      ].join('\n'));
      writeFileSync(repo.path('.pre-commit-config.yaml'), 'repos:\n  - repo: local\n    hooks:\n      - id: existing-hook\n        entry: echo existing\n');

      const first = await runCli(repo, ['init', '--blocking']);
      expect(first.code).toBe(0);
      expect(first.stdout).toContain('framework-managed pre-commit hook detected');
      expect(first.stdout).not.toContain('required action');
      // The gateforge hook block is appended to the FRAMEWORK config —
      // the framework then runs it on every commit.
      const precommit = readFileSync(repo.path('.pre-commit-config.yaml'), 'utf8');
      expect(precommit).toContain('gateforge-check');
      expect(precommit).toContain('existing-hook');
      expect(existsSync(repo.path('.gateforge/hooks/gateforge-check.mjs'))).toBe(true);
      // Idempotent rerun stays green.
      const second = await runCli(repo, ['init', '--blocking']);
      expect(second.code).toBe(0);
      expect(readFileSync(repo.path('.pre-commit-config.yaml'), 'utf8').split('id: gateforge-check').length - 1).toBe(1);
    });
  });

  it('--blocking wires the pre-commit hook, check script, and CI template', async () => {
    await withTempRepo({}, async (repo) => {
      const first = await runCli(repo, ['init', '--blocking']);
      expect(first.code).toBe(0);
      const hook = repo.path('.gateforge/hooks/gateforge-check.mjs');
      expect(existsSync(hook)).toBe(true);
      const precommit = readFileSync(repo.path('.pre-commit-config.yaml'), 'utf8');
      expect(precommit).toContain('gateforge-check');
      expect(existsSync(repo.path('.gateforge/ci/gitlab-gateforge.yml'))).toBe(true);
      expect(readFileSync(repo.path('.gitlab-ci.yml'), 'utf8')).toContain('gitlab-gateforge.yml');
      // The CI template is the strict E2E gate (plan Phase 6): supervised
      // receipt seal + require-e2e check, never an optional/static-only job.
      const ciTemplate = readFileSync(repo.path('.gateforge/ci/gitlab-gateforge.yml'), 'utf8');
      expect(ciTemplate).toContain('gateforge test-gates --changed');
      expect(ciTemplate).toContain('gateforge check --changed --require-e2e');
      // Pinned engine install (lockfile-based), with a version assertion.
      expect(ciTemplate).toContain('npm ci');
      expect(ciTemplate).toContain('GATEFORGE_VERSION');
      // The honest limits are carried in the template comments: the
      // signing material boundary, the approved-policy pin (E17), and
      // the server-side settings act.
      expect(ciTemplate).toContain('GATEFORGE_WITNESS_VERIFIER_KEY');
      expect(ciTemplate).toContain('GATEFORGE_APPROVED_POLICY_DIGEST');
      expect(ciTemplate).toContain('APPROVED POLICY PIN');
      expect(ciTemplate).toContain('ENFORCEMENT_UNTRUSTED');
      expect(ciTemplate).toContain('pipeline execution policy');
      expect(ciTemplate).toContain('Pipelines must succeed');
      expect(ciTemplate).toContain('Protected branches');
      // The template must stay valid, loadable YAML with the gate job —
      // and the job must never be optional (no allow_failure/manual).
      const parsed = parseYaml(ciTemplate) as Record<string, Record<string, unknown>>;
      expect(Object.keys(parsed)).toContain('gateforge:e2e-gate');
      const gateJob = parsed['gateforge:e2e-gate'] ?? {};
      expect(gateJob['allow_failure']).toBeUndefined();
      expect(gateJob['when']).toBeUndefined();
      expect(gateJob['rules']).toEqual([{ if: '$CI_PIPELINE_SOURCE == "merge_request_event"' }]);
      // idempotent: second run must not duplicate the hook entry
      const again = await runCli(repo, ['init', '--blocking']);
      expect(again.code).toBe(0);
      expect(again.stdout).toContain('exists, leaving untouched');
      const count = readFileSync(repo.path('.pre-commit-config.yaml'), 'utf8').split('id: gateforge-check').length - 1;
      expect(count).toBe(1);
    });
  });

  it('without --blocking it writes no enforcement files and prints the tip', async () => {
    await withTempRepo({}, async (repo) => {
      const { code, stdout } = await runCli(repo, ['init']);
      expect(code).toBe(0);
      expect(existsSync(repo.path('.gateforge/hooks/gateforge-check.mjs'))).toBe(false);
      expect(existsSync(repo.path('.pre-commit-config.yaml'))).toBe(false);
      expect(stdout).toContain('--blocking');
    });
  });

  it('preconfigures trusted detectors and makes discovery runnable', async () => {
    await withTempRepo({}, async (repo) => {
      const initialized = await runCli(repo, ['init', '--languages', 'python,javascript,typescript']);
      expect(initialized.code).toBe(0);
      const config = loadConfig(join(repo.root, '.gateforge.yml'));
      expect(config.plugins.map((plugin) => plugin.id)).toEqual([
        'gateforge.pack-fastapi',
        'gateforge.pack-sqlalchemy',
        'gateforge.pack-http',
        'gateforge.pack-task',
      ]);
      expect(config.plugins.every((plugin) => plugin.transport === 'in-process')).toBe(true);
      expect(config.project.paths.include).toEqual([
        '**/*.py',
        '**/*.js',
        '**/*.jsx',
        '**/*.mjs',
        '**/*.cjs',
        '**/*.ts',
        '**/*.tsx',
      ]);
      expect(config.project.paths.exclude).toContain('**/.venv/**');

      const discovered = await runCli(repo, ['discover']);
      expect(discovered.code).toBe(0);
      expect(discovered.stderr).toBe('');
    });
  });

  it('is idempotent and never overwrites user files', async () => {
    await withTempRepo({}, async (repo) => {
      const first = await runCli(repo, ['init']);
      expect(first.code).toBe(0);

      // The user edits the generated config; init must leave it alone.
      const configPath = repo.path('.gateforge.yml');
      const userEdit = readFileSync(configPath, 'utf8') + '\n# user customization\nlanguages: [ruby]\n';
      repo.writeFiles({ '.gateforge.yml': userEdit });

      const second = await runCli(repo, ['init']);
      expect(second.code).toBe(0);
      expect(second.stdout).not.toContain('created:');
      expect(second.stdout).toContain('exists, leaving untouched');
      expect(readFileSync(configPath, 'utf8')).toBe(userEdit);
    });
  });

  it('honors --languages and rejects an empty list', async () => {
    await withTempRepo({}, async (repo) => {
      const { code, stdout } = await runCli(repo, ['init', '--languages', 'python,node']);
      expect(code).toBe(0);
      const config = readFileSync(repo.path('.gateforge.yml'), 'utf8');
      expect(config).toContain('- python');
      expect(config).toContain('- node');
      expect(stdout).toContain('created:');
    });
    await withTempRepo({}, async (repo) => {
      const { code, stderr } = await runCli(repo, ['init', '--languages', ' , ']);
      expect(code).toBe(2);
      expect(stderr).toContain('--languages');
    });
  });

  it('keeps existing skeleton files when the config is regenerated', async () => {
    await withTempRepo({}, async (repo) => {
      const first = await runCli(repo, ['init']);
      expect(first.code).toBe(0);
      // A waiver file the user dropped into the skeleton survives init.
      repo.writeFiles({ '.gateforge/waivers/custom.json': '{"user": true}' });
      const second = await runCli(repo, ['init']);
      expect(second.code).toBe(0);
      expect(readFileSync(repo.path('.gateforge/waivers/custom.json'), 'utf8')).toBe(
        '{"user": true}',
      );
    });
  });
});