/**
 * `gateforge migrate`: the one command a 0.9 repository needs before it
 * can run anything else.
 *
 * The properties under test are the ones that make it safe on a real
 * adopted repository: a preview that writes nothing, a confirmed run that
 * changes exactly the config text (original bytes plus one inserted
 * block), lists that come back identical, and a policy digest that moves
 * once and then stays put.
 */
import { existsSync, readFileSync } from 'node:fs';
import { describe, expect, it } from 'vitest';
import { loadConfig, withTempRepo, type TempRepo } from '@gate-forge/core';
import { loadCacheExclusions, readLegacyCacheExclusions } from '../src/cache-exclusions.js';
import { loadDocsExclusions, readLegacyDocsExclusions } from '../src/docs-exclusions.js';
import { trustedPolicyDigestForConfig } from '../src/execution.js';
import { configYml, installFixture, runCli } from './helpers.js';

async function legacyRepo(repo: TempRepo): Promise<void> {
  installFixture(repo);
  repo.writeFiles({
    'docs/guide.md': '# Owner-only guide\n',
    'src/__pycache__/accounts.cpython-313.pyc': 'generated bytecode\n',
    '.gateforge/docs-exclusions.yml': 'schemaVersion: 1\nfolders:\n  - docs\n',
    '.gateforge/cache-exclusions.yml':
      'schemaVersion: 1\nfiles:\n  - "src/__pycache__/accounts.cpython-313.pyc"\n',
  });
}

describe('gateforge migrate', () => {
  it('previews the exact change and writes nothing', async () => {
    await withTempRepo({}, async (repo) => {
      await legacyRepo(repo);
      const before = readFileSync(repo.path('.gateforge.yml'), 'utf8');

      const preview = await runCli(repo, ['migrate']);
      expect(preview.code, `${preview.stdout}\n${preview.stderr}`).toBe(0);
      expect(preview.stdout).toContain('evidence.exclude.docs (1)');
      expect(preview.stdout).toContain('evidence.exclude.cache (1)');
      expect(preview.stdout).toContain('deleted: .gateforge/docs-exclusions.yml');
      expect(preview.stdout).toContain('deleted: .gateforge/cache-exclusions.yml');
      expect(preview.stdout).toContain('+evidence:');
      expect(preview.stdout).toContain('dry run only');
      expect(readFileSync(repo.path('.gateforge.yml'), 'utf8')).toBe(before);
      expect(existsSync(repo.path('.gateforge/docs-exclusions.yml'))).toBe(true);
      expect(existsSync(repo.path('.gateforge/cache-exclusions.yml'))).toBe(true);
    });
  });

  it('writes only the inserted block, deletes both files, and keeps every list', async () => {
    await withTempRepo({}, async (repo) => {
      await legacyRepo(repo);
      const before = readFileSync(repo.path('.gateforge.yml'), 'utf8');
      const legacyConfig = loadConfig(repo.path('.gateforge.yml'));
      const legacyDocs = readLegacyDocsExclusions(repo.root, legacyConfig);
      const legacyCache = readLegacyCacheExclusions(repo.root, legacyConfig);
      expect(legacyDocs).toEqual(['docs']);
      expect(legacyCache).toEqual(['src/__pycache__/accounts.cpython-313.pyc']);
      const digestBefore = trustedPolicyDigestForConfig(repo.root, legacyConfig);

      const applied = await runCli(repo, ['migrate', '--confirm']);
      expect(applied.code, `${applied.stdout}\n${applied.stderr}`).toBe(0);
      expect(applied.stdout).toContain('policy inputs changed: re-pin the approved digest');

      const after = readFileSync(repo.path('.gateforge.yml'), 'utf8');
      // Original bytes, in order, plus exactly one inserted block.
      expect(after).toBe(
        `${before}evidence:\n  exclude:\n    docs:\n      - "docs"\n    cache:\n      - "src/__pycache__/accounts.cpython-313.pyc"\n`,
      );
      expect(existsSync(repo.path('.gateforge/docs-exclusions.yml'))).toBe(false);
      expect(existsSync(repo.path('.gateforge/cache-exclusions.yml'))).toBe(false);

      // The loaders now read the config and return exactly the old lists.
      const config = loadConfig(repo.path('.gateforge.yml'));
      expect(loadDocsExclusions(repo.root, config)).toEqual(legacyDocs);
      expect(loadCacheExclusions(repo.root, config)).toEqual(legacyCache);

      // The digest moved exactly once and is stable afterwards.
      const digestAfter = trustedPolicyDigestForConfig(repo.root, config);
      expect(digestAfter).not.toBe(digestBefore);
      expect(trustedPolicyDigestForConfig(repo.root, loadConfig(repo.path('.gateforge.yml')))).toBe(digestAfter);

      // And the gate runs again without a refusal.
      const next = await runCli(repo, ['next']);
      expect(next.stderr).not.toContain('gateforge migrate');
    });
  });

  it('is idempotent and says so', async () => {
    await withTempRepo({}, async (repo) => {
      await legacyRepo(repo);
      expect((await runCli(repo, ['migrate', '--confirm'])).code).toBe(0);
      const after = readFileSync(repo.path('.gateforge.yml'), 'utf8');

      const again = await runCli(repo, ['migrate', '--confirm']);
      expect(again.code, `${again.stdout}\n${again.stderr}`).toBe(0);
      expect(again.stdout).toContain('nothing to migrate');
      expect(readFileSync(repo.path('.gateforge.yml'), 'utf8')).toBe(after);
    });
  });

  it('extends an existing evidence block instead of re-serializing the config', async () => {
    await withTempRepo({}, async (repo) => {
      installFixture(repo);
      repo.writeFiles({
        'docs/guide.md': '# Guide\n',
        '.gateforge.yml': `# owner note\n${configYml({ evidence: { docs: ['docs'] } })}`,
        '.gateforge/docs-exclusions.yml': 'schemaVersion: 1\nfolders:\n  - docs\n',
      });
      const before = readFileSync(repo.path('.gateforge.yml'), 'utf8');

      const applied = await runCli(repo, ['migrate', '--confirm']);
      expect(applied.code, `${applied.stdout}\n${applied.stderr}`).toBe(0);
      const after = readFileSync(repo.path('.gateforge.yml'), 'utf8');
      expect(after).toContain('# owner note');
      expect(after).toContain('clock:\n  mode: fixed');
      // The already-declared docs list is untouched, and the block is
      // written once (not appended twice).
      expect(after.match(/evidence:/g)).toHaveLength(1);
      expect(after.match(/- "docs"/g)).toHaveLength(1);
      expect(after.startsWith(before)).toBe(true);
    });
  });

  it('refuses an evidence block it cannot extend safely, by name', async () => {
    await withTempRepo({}, async (repo) => {
      installFixture(repo);
      repo.writeFiles({
        'docs/guide.md': '# Guide\n',
        '.gateforge.yml': `${configYml()}\nevidence:\n  exclude:\n    docs: ["docs"]\n`,
        '.gateforge/docs-exclusions.yml': 'schemaVersion: 1\nfolders:\n  - docs\n',
      });
      const before = readFileSync(repo.path('.gateforge.yml'), 'utf8');

      const refused = await runCli(repo, ['migrate', '--confirm']);
      expect(refused.code).toBe(2);
      expect(refused.stderr).toContain('declares docs inline');
      expect(refused.stderr).toContain('.gateforge.yml');
      expect(readFileSync(repo.path('.gateforge.yml'), 'utf8')).toBe(before);
      expect(existsSync(repo.path('.gateforge/docs-exclusions.yml'))).toBe(true);
    });
  });

  it('rejects unknown flags and names itself in --help', async () => {
    await withTempRepo({}, async (repo) => {
      installFixture(repo);
      const unknown = await runCli(repo, ['migrate', '--json']);
      expect(unknown.code).toBe(2);
      expect(unknown.stderr).toContain("unknown flag '--json'");
      const help = await runCli(repo, ['migrate', '--help']);
      expect(help.code).toBe(0);
      expect(help.stdout).toContain('usage: gateforge migrate');
      expect(help.stdout).toContain('evidence.exclude.docs');
    });
  });
});
