/**
 * 0.9.0 D2 (problem 24), end to end through the REAL CLI: Gateforge's own
 * scaffold/policy files are POLICY INPUTS, not unmapped product changes.
 *
 * What the bug was: on a real repository the setup/adopt commit could not be
 * committed. `init` and `adopt` write the config, the policy documents, the
 * baseline records, the generated gate wiring and the owner's CI/pre-commit
 * wiring — and `check --changed` in strict E2E mode treated every one of
 * those writes as an unmapped PRODUCT change (CHANGE_UNMAPPED, e.g. 16
 * entries on one repository), while their gate-defining nature expanded the
 * scope to the whole repository and re-graded every ADOPTED obligation as
 * blocking ENFORCEMENT_UNTRUSTED. The owner had to pass `--no-verify` for
 * the one commit that installs the gate.
 *
 * The fix: those exact paths are policy inputs — governed by the
 * owner-approved policy digest (a pin mismatch still blocks) and never an
 * unmapped product change — and a change set whose WHOLE content is policy
 * input keeps the adopted baseline's forgiveness, because it cannot change
 * product behavior. Everything else keeps today's treatment: the security
 * property that a policy-only change still EXPANDS the scope and that new
 * or weakened obligations still block is covered here too.
 */
import { describe, expect, it } from 'vitest';
import { loadConfig, withTempRepo, type TempRepo } from '@gate-forge/core';
import { configYml, installFixture, POLICIES_YML, runCli, stubPlaywrightFiles } from './helpers.js';
import { ADAPTER, SPECS, STUB_CLI } from './reseal-e2e-fixture.js';
import { trustedPolicyDigestForConfig } from '../src/execution.js';
import {
  ENGINE_STATE_IGNORE_COMMENT,
  ENGINE_STATE_IGNORE_ENTRIES,
} from '../src/gateforge-owned.js';

/** The orders obligation: never claimed by any test — adopted debt. */
const OBLIGATION_ORDERS = 'tenant.orders:persistence:read';

/** A product file that no discovered resource claims (unmapped change). */
const UNMAPPED_PRODUCT_FILE = 'src/orders/loyalty.js';

/** The managed `.gitignore` block exactly as `init` appends it. */
const IGNORE_BLOCK = `${ENGINE_STATE_IGNORE_COMMENT}\n${ENGINE_STATE_IGNORE_ENTRIES.join('\n')}\n`;

/** The CI config with Gateforge's managed include still wired. */
const CI_WITH_GATE = `stages: [gate]
include:
 - local: '.gateforge/ci/gitlab-gateforge.yml'
`;

/** The same CI config with the Gateforge gate job removed. */
const CI_WITHOUT_GATE = `stages: [gate]
`;

/** The pre-commit config carrying Gateforge's managed block. */
const PRE_COMMIT_WITH_GATE = `repos:
  - repo: local
    hooks:
      - id: gateforge-check
        name: gateforge check
        entry: node .gateforge/hooks/gateforge-check.mjs
        language: system
        pass_filenames: false
`;

/**
 * The setup/adopt commit's Gateforge-owned half: policy documents, generated
 * gate wiring, the baseline records `adopt` wrote, and the owner's managed
 * CI/pre-commit wiring.
 */
const SETUP_FILES: Record<string, string> = {
  '.gateforge/policies.yml': `${POLICIES_YML}\n# reviewed for the adoption commit\n`,
  '.gateforge/ci/gitlab-gateforge.yml': '# Generated by Gateforge\n',
  '.gateforge/hooks/gateforge-check.mjs': "// generated gate hook\nexport default {};\n",
  '.gitlab-ci.yml': CI_WITH_GATE,
  '.pre-commit-config.yaml': PRE_COMMIT_WITH_GATE,
  'GATEFORGE.md': '# Gateforge\n\nRun `gateforge check --changed` before committing.\n',
};

interface Report {
  summary: {
    blocking: number;
    baselinedObligations?: number;
    neverWitnessedBaselinedObligations?: number;
  };
  blocking: Array<{ name: string | null; cause?: string | null; nextAction?: string | null; detail: string }>;
}

/**
 * Installs the two-resource strict-E2E repository and adopts
 * its red set. `baseIgnore` is the base revision's `.gitignore`
 * (the default already carries the engine-state entry).
 * `adoptedDebt` writes `enforcement.adoptedDebt` (0.10.4); absent is the
 * `lenient` default, under which a `.gitignore` line outside the managed
 * block — an ignore control, so no product behaviour — keeps the adopted
 * debt forgiven. A test that pins the 0.10.3 re-grade asks for `strict`.
 */
async function installAndAdopt(
  repo: TempRepo,
  baseIgnore = '.gateforge/test-gates/\nnode_modules/\n',
  adoptedDebt: 'lenient' | 'strict' | null = null,
): Promise<void> {
  installFixture(repo);
  repo.writeFiles({
    ...SPECS,
    '.gateforge/adapters/accounts.mjs': ADAPTER,
    '.gateforge/adapters/orders.mjs': ADAPTER,
    '.gateforge.yml':
      `enforcement:\n  strictE2E: true\n${adoptedDebt === null ? '' : `  adoptedDebt: ${adoptedDebt}\n`}${configYml()}`,
    ...stubPlaywrightFiles(STUB_CLI),
    '.gitignore': baseIgnore,
  });
  repo.commitFiles({}, 'base');
  const adopted = await runCli(repo, ['adopt']);
  expect(adopted.code, `${adopted.stdout}\n${adopted.stderr}`).toBe(0);
}

/**
 * Stages the setup/adopt commit (everything Gateforge wrote) plus optional
 * extra files, and returns the approved-policy pin for the staged revision.
 *
 * Args:
 *   repo: the fixture repository.
 *   extra: additional files to stage with the setup commit.
 *
 * Returns:
 *   string: the candidate's current trusted policy digest.
 */
function stageSetupCommit(repo: TempRepo, extra: Record<string, string> = {}): string {
  repo.writeFiles({ ...SETUP_FILES, ...extra });
  repo.stage();
  return trustedPolicyDigestForConfig(repo.root, loadConfig(repo.path('.gateforge.yml')));
}

/** Runs `check --changed` with the owner-approved policy revision pinned. */
async function runChangedCheck(repo: TempRepo, pin: string, extraArgs: readonly string[] = []) {
  return runCli(repo, ['check', '--changed', '--format', 'json', ...extraArgs], {
    GATEFORGE_APPROVED_POLICY_DIGEST: pin,
  });
}

describe('Gateforge-owned policy inputs in the changed scope (real CLI)', () => {
  it('commits the setup/adopt commit in strict E2E mode without --no-verify', async () => {
    await withTempRepo({}, async (repo) => {
      await installAndAdopt(repo);
      const pin = stageSetupCommit(repo);

      const run = await runChangedCheck(repo, pin);
      const report = JSON.parse(run.stdout) as Report;
      const output = `${run.stdout}\n${run.stderr}`;

      // Not one Gateforge-owned write is an unmapped product change.
      expect(
        report.blocking.filter((entry) => entry.cause === 'CHANGE_UNMAPPED'),
        output,
      ).toEqual([]);
      // The adopted debt is still evaluated and still reported — a green
      // setup commit is not a silently forgone repository.
      expect(report.summary.baselinedObligations ?? 0).toBeGreaterThan(0);
      expect(report.summary.neverWitnessedBaselinedObligations ?? 0).toBeGreaterThan(0);
      expect(run.code, output).toBe(0);
    });
  }, 240_000);

  it('a product file in the same change set still blocks, and names the step that attributes it', async () => {
    await withTempRepo({}, async (repo) => {
      await installAndAdopt(repo);
      const pin = stageSetupCommit(repo, { [UNMAPPED_PRODUCT_FILE]: 'export const tier = 1;\n' });

      const run = await runChangedCheck(repo, pin);
      const report = JSON.parse(run.stdout) as Report;
      const output = `${run.stdout}\n${run.stderr}`;
      const unmapped = report.blocking.filter((entry) => entry.cause === 'CHANGE_UNMAPPED');

      expect(unmapped.map((entry) => entry.name), output).toEqual([UNMAPPED_PRODUCT_FILE]);
      // Problem 26: the remediation names a step that actually attributes the
      // file instead of "map the changed resource", which nothing can do.
      expect(unmapped[0]?.nextAction ?? '', output).toContain(`gateforge explain ${UNMAPPED_PRODUCT_FILE}`);
      // The adopted debt is re-graded once product behavior can have changed.
      expect(output).toContain('ENFORCEMENT_UNTRUSTED');
      expect(output).toContain(OBLIGATION_ORDERS);
      expect(run.code, output).not.toBe(0);
    });
  }, 240_000);

  it('removing the Gateforge gate job from the CI config keeps its blocking treatment', async () => {
    await withTempRepo({}, async (repo) => {
      await installAndAdopt(repo);
      // `.gitlab-ci.yml` is a policy input only WHILE Gateforge's managed
      // block is wired: deleting the gate job must not self-authorize.
      const pin = stageSetupCommit(repo, { '.gitlab-ci.yml': CI_WITHOUT_GATE });

      const run = await runChangedCheck(repo, pin);
      const report = JSON.parse(run.stdout) as Report;
      const output = `${run.stdout}\n${run.stderr}`;

      expect(
        report.blocking
          .filter((entry) => entry.cause === 'CHANGE_UNMAPPED')
          .map((entry) => entry.name),
        output,
      ).toEqual(['.gitlab-ci.yml']);
      expect(run.code, output).not.toBe(0);
    });
  }, 240_000);

  it('a policy-input change with a mismatching approved digest still blocks', async () => {
    await withTempRepo({}, async (repo) => {
      await installAndAdopt(repo);
      stageSetupCommit(repo);

      const run = await runChangedCheck(repo, 'a'.repeat(64), ['--require-e2e']);
      const output = `${run.stdout}\n${run.stderr}`;

      // The policy revision is the owner's approval; a change to the files it
      // covers is governed by the pin, not by the change set's shape.
      expect(output).toContain('does not match the owner-approved revision');
      expect(output).toContain('ENFORCEMENT_UNTRUSTED');
      expect(run.code, output).not.toBe(0);
    });
  }, 240_000);

  it('a setup commit that also stages the .gitignore engine-state block stays product-behavior-neutral', async () => {
    await withTempRepo({}, async (repo) => {
      // The base revision's `.gitignore` carries none of
      // Gateforge's block: `init` appends it as part of the
      // setup commit, exactly like a real first setup.
      await installAndAdopt(repo, 'node_modules/\n');
      const pin = stageSetupCommit(repo, {
        '.gitignore': `node_modules/\n${IGNORE_BLOCK}`,
      });

      const run = await runChangedCheck(repo, pin);
      const report = JSON.parse(run.stdout) as Report;
      const output = `${run.stdout}\n${run.stderr}`;

      // The managed block is engine wiring, not a product
      // change: no unmapped entry, and the adopted debt stays
      // forgiven.
      expect(
        report.blocking.filter((entry) => entry.cause === 'CHANGE_UNMAPPED'),
        output,
      ).toEqual([]);
      expect(report.summary.baselinedObligations ?? 0).toBeGreaterThan(0);
      expect(report.summary.neverWitnessedBaselinedObligations ?? 0).toBeGreaterThan(0);
      expect(run.code, output).toBe(0);
    });
  }, 240_000);

  it('with `adoptedDebt: strict`, a .gitignore line outside the managed block re-grades the adopted debt', async () => {
    await withTempRepo({}, async (repo) => {
      // 0.10.4: the LENIENT default keeps the adopted debt forgiven here —
      // an ignore control carries no product behaviour, so a `.gitignore`
      // line outside the managed block is still neutral and its change set
      // is not the re-grade trigger. The 0.10.3 re-grade is the behaviour
      // an owner opts into, and this is where it stays pinned.
      await installAndAdopt(repo, 'node_modules/\n', 'strict');
      // `dist/` is the owner's own ignore wiring — not
      // Gateforge's managed block — so the change set is not
      // product-behavior-neutral. `.gitignore` keeps its
      // gate-defining scope-control treatment (it expands the
      // scope), exactly as it was before the ignore-wiring
      // classification existed.
      const pin = stageSetupCommit(repo, {
        '.gitignore': `node_modules/\n${IGNORE_BLOCK}dist/\n`,
      });

      const run = await runChangedCheck(repo, pin);
      const output = `${run.stdout}\n${run.stderr}`;

      // The adopted debt is re-graded once product behavior
      // can have changed: the setup commit blocks, the
      // adopted obligation turns ENFORCEMENT_UNTRUSTED again.
      expect(output).toContain('ENFORCEMENT_UNTRUSTED');
      expect(output).toContain(OBLIGATION_ORDERS);
      expect(run.code, output).not.toBe(0);
    });
  }, 240_000);

  it('a staged setup commit with the .gitignore engine-state block passes the staged gate', async () => {
    await withTempRepo({}, async (repo) => {
      // The base revision's `.gitignore` carries none of
      // Gateforge's block: `init` appends it as part of
      // the setup commit, and the pre-commit hook gates
      // exactly this commit via `check --staged`.
      await installAndAdopt(repo, 'node_modules/\n');
      const pin = stageSetupCommit(repo, {
        '.gitignore': `node_modules/\n${IGNORE_BLOCK}`,
      });

      const run = await runCli(
        repo,
        ['check', '--staged', '--format', 'json'],
        { GATEFORGE_APPROVED_POLICY_DIGEST: pin },
      );
      const report = JSON.parse(run.stdout) as Report;
      const output = `${run.stdout}\n${run.stderr}`;

      // The managed block is engine wiring in the staged
      // flow too: no unmapped entry, and the adopted debt
      // stays forgiven (the staged gate is the one the
      // pre-commit hook runs on the setup commit).
      expect(
        report.blocking.filter((entry) => entry.cause === 'CHANGE_UNMAPPED'),
        output,
      ).toEqual([]);
      expect(report.summary.baselinedObligations ?? 0).toBeGreaterThan(0);
      expect(report.summary.neverWitnessedBaselinedObligations ?? 0).toBeGreaterThan(0);
      expect(run.code, output).toBe(0);
    });
  }, 240_000);

  it('with `adoptedDebt: strict`, a staged setup commit with a .gitignore line outside the managed block blocks', async () => {
    await withTempRepo({}, async (repo) => {
      // 0.10.4: the LENIENT default forgives the adopted debt for this
      // change set, so the fail-closed re-grade it asserts is the
      // behaviour an owner asks for by name.
      await installAndAdopt(repo, 'node_modules/\n', 'strict');
      const pin = stageSetupCommit(repo, {
        '.gitignore': `node_modules/\n${IGNORE_BLOCK}dist/\n`,
      });

      const run = await runCli(
        repo,
        ['check', '--staged', '--format', 'json'],
        { GATEFORGE_APPROVED_POLICY_DIGEST: pin },
      );
      const output = `${run.stdout}\n${run.stderr}`;

      // Fail closed: the staged flow cannot prove the
      // non-managed line is wiring, so the adopted debt
      // is re-graded and the setup commit blocks.
      expect(output).toContain('ENFORCEMENT_UNTRUSTED');
      expect(output).toContain(OBLIGATION_ORDERS);
      expect(run.code, output).not.toBe(0);
    });
  }, 240_000);
});