/**
 * Adapter scaffolding: turning the compiled graph + route inventory
 * into a REVIEWED-CANDIDATE adapter per business resource.
 *
 * The rules this planner follows are the plan's, and they are the
 * opposite of "just generate something that runs":
 *
 * - it NEVER overwrites: a resource that already has an adapter is
 *   reported as `exists` and left alone;
 * - it marks EVERY guess, in the generated file's own header, where a
 *   reviewer sees it before the file is ever run;
 * - it refuses to write a file it cannot write honestly (unknown
 *   target fingerprint, no route to read from) and says why instead;
 * - anything left for a human is listed as `needs you`, with the
 *   reason — the command prints it, the guide explains it;
 * - it writes ONLY from routes the engine LINKED to the resource: a
 *   path that merely names it is a candidate for a human to confirm,
 *   and a route linked to a different resource is someone else's;
 * - it never takes a route with a literal segment between the
 *   resource and its id as a by-id read (`/shipments/carrier/{id}`
 *   reads a carrier through a shipment);
 * - it writes a LIST-ONLY adapter when the app serves a complete
 *   collection and no by-id route at all — the kit resolves the
 *   member out of the collection — and says in the header that this
 *   is slower than a real read;
 * - a route that exists but whose endpoint plane is unanswered is
 *   NAMED with that blocker, never reported as absent.
 */
import type { GraphResource, HttpRouteCandidate } from '@gate-forge/core';
import {
  literalTailAfterResource,
  routesForResource,
  splitRoutePath,
  unresolvedRoutesForResource,
  type UnresolvedRoute,
} from './adapter-audit.js';

/** What the planner decided for one resource. */
export type ScaffoldStatus = 'create' | 'exists' | 'needs-you';

/** One resource's scaffolding decision. */
export interface ScaffoldPlan {
  /** The plane-qualified resource id (also the adapter file name). */
  resourceId: string;
  /** Bare resource name, for messages. */
  name: string;
  /** What the planner decided. */
  status: ScaffoldStatus;
  /** The generated module text (`null` unless status is `create`). */
  source: string | null;
  /** Every guess baked into the generated file. */
  guesses: string[];
  /** What still needs a human, with the reason. */
  needsYou: string[];
}

/** One business resource plus the adapter name it is bound to. */
export interface AdapterTarget {
  /** The graph resource (raw id: a blocked resource has no bound id). */
  resource: GraphResource;
  /** The adapter file name the classifier expects. */
  adapterId: string;
  /** Proven delete semantics, or null when the classifier could not. */
  deleteSemantics: 'hard' | 'archive' | null;
}

/** Everything the planner reads. */
export interface ScaffoldInput {
  /** Business resources the classifier demands an adapter for. */
  targets: readonly AdapterTarget[];
  /** The compiled GET route inventory. */
  routes: readonly HttpRouteCandidate[];
  /** Adapter names already present in the adapters directory. */
  existing: readonly string[];
  /** The run's target fingerprint, when the environment declares one. */
  environmentFingerprint: string | null;
  /**
   * GET routes the runtime inventory omits because the endpoint's
   * plane is unanswered: the scaffolder names them instead of
   * reporting the resource as unserved.
   */
  unresolvedRoutes: readonly UnresolvedRoute[];
  /**
   * Route paths no app mounts (the endpoint is declared by a standalone
   * router): a path derived from one of these is marked as an explicit
   * guess, never silently trusted.
   */
  standalonePaths: readonly string[];
}

/**
 * Renders the guess block of a generated file.
 *
 * Args:
 *   resourceId: the resource the adapter proves.
 *   guesses: every guess baked into the file.
 *   notice: the shape warning the header carries above the guess list
 *     (a list-only adapter reads every member out of the collection,
 *     and that must be visible in the file itself).
 *
 * Returns:
 *   string: the header comment (empty guesses render as a single line).
 */
function guessComment(
  resourceId: string,
  guesses: readonly string[],
  notice?: string,
): string {
  const lines = [
    '/**',
    ` * ${resourceId} — GENERATED by \`gateforge adapters scaffold\`.`,
    ' *',
    ' * A STARTING POINT, never proof: the gate grades this file exactly',
    ' * like a hand-written adapter. Review every line below before you',
    ' * trust it, and run `gateforge adapters check --probe` afterwards.',
    ' *',
    ...(notice === undefined
      ? []
      : [' *', ...notice.split('\n').map((line) => ` * ${line}`), ' *']),
    ' * Guesses in this file:',
    ...(guesses.length === 0
      ? [' *   (none — every value below was derived from the compiled graph)']
      : guesses.map((guess, index) => ` *   ${String(index + 1)}. ${guess}`)),
    ' */',
  ];
  return lines.join('\n');
}

/**
 * Whether a route's literal prefix still carries an INNER positional
 * segment (e.g. `/api/v1/contracts/:contractId/invoices`).
 *
 * Args:
 *   prefix: the literal prefix `splitRoutePath` left behind.
 *
 * Returns:
 *   boolean: true when a parameter sits before the collection name.
 */
function hasInnerParam(prefix: string): boolean {
  return prefix
    .split('/')
    .some((segment) => segment.startsWith(':') || segment === '{}');
}

/** Column names that usually mark a soft-deleted row, not a removed one. */
const SOFT_DELETE_COLUMNS: Record<string, true> = {
  is_active: true,
  active: true,
  archived: true,
  archived_at: true,
  deleted_at: true,
  is_deleted: true,
};

/** Column-name fragments that mark a credential, never a projected field. */
const SECRET_COLUMN_PATTERN: RegExp = /password|secret|token|hash|api[-_]?key|private[-_]?key/;

/** Attribute keys a detector may use to mark columns as non-projectable. */
const SECRET_COLUMN_KEYS: readonly string[] = [
  'secretColumns',
  'secretFields',
  'sensitiveFields',
  'nonProjectableFields',
];

/**
 * The business fields a scaffolder can honestly project, and the
 * declared columns it deliberately left out.
 *
 * Every column the graph declares for the table is projected — the
 * obligations observe read-only columns and foreign keys, not only
 * the updateable ones — except the primary key (that IS the id) and
 * the columns that must never leave the app.
 *
 * Args:
 *   resource: the business resource.
 *
 * Returns:
 *   {fields: string[], excluded: string[]}: the projected columns and
 *   the excluded ones, each sorted and deduplicated.
 */
function projectedFields(resource: GraphResource): { fields: string[]; excluded: string[] } {
  // The primary key IS the entity id, so it is never a projected
  // field — whichever layer declared it (the classification, or the
  // table's own primary-key facts).
  const primaryKey = new Set([
    ...(resource.classification?.primaryKey ?? []),
    ...attributeColumns(resource.attributes['primaryKeyColumns'], 'name'),
  ]);
  const declaredSecrets = new Set(
    SECRET_COLUMN_KEYS.flatMap((key) => attributeColumns(resource.attributes[key], 'name')),
  );
  const fields: string[] = [];
  const excluded: string[] = [];
  for (const column of declaredColumns(resource)) {
    const isSecret =
      declaredSecrets.has(column) || SECRET_COLUMN_PATTERN.test(column.toLowerCase());
    if (primaryKey.has(column) || isSecret) excluded.push(column);
    else fields.push(column);
  }
  return { fields, excluded };
}

/**
 * Reads column names out of one column-bearing graph attribute, in
 * either of the two shapes a detector emits: bare names, or records
 * that carry the name under `name` / `column`.
 *
 * Args:
 *   value: the raw attribute value (never trusted).
 *   key: the property holding the name for the record shape.
 *
 * Returns:
 *   string[]: every non-empty column name in the attribute.
 */
function attributeColumns(value: unknown, key: 'name' | 'column'): string[] {
  if (!Array.isArray(value)) return [];
  const names: string[] = [];
  for (const entry of value) {
    if (typeof entry === 'string') {
      if (entry.length > 0) names.push(entry);
      continue;
    }
    if (typeof entry === 'object' && entry !== null && key in entry) {
      const name = entry[key];
      if (typeof name === 'string' && name.length > 0) names.push(name);
    }
  }
  return names;
}

/**
 * Every column the compiled graph declares for one table.
 *
 * Detectors own their attribute vocabulary, so this reads the
 * column-bearing attributes the graph actually carries: the full
 * column list a detector emits (`columnNames` / `columns`), the
 * primary-key, foreign-key, soft-delete and updateable field facts,
 * and the classification's own identity/updateable declarations.
 *
 * Args:
 *   resource: the business resource.
 *
 * Returns:
 *   string[]: the declared column names, sorted and deduplicated.
 */
function declaredColumns(resource: GraphResource): string[] {
  const attributes = resource.attributes;
  const columns = [
    ...attributeColumns(attributes['columnNames'], 'name'),
    ...attributeColumns(attributes['columns'], 'name'),
    ...attributeColumns(attributes['primaryKeyColumns'], 'name'),
    ...attributeColumns(attributes['foreignKeyReferences'], 'column'),
    ...attributeColumns(attributes['softDeleteCandidateFields'], 'name'),
    ...attributeColumns(attributes['updateableFields'], 'name'),
    ...(resource.classification?.primaryKey ?? []),
    ...(resource.classification?.lifecycle.updateableFields ?? []),
  ];
  return [...new Set(columns)].sort();
}

/**
 * How the table's delete semantics look to the graph.
 *
 * Args:
 *   resource: the business resource.
 *
 * Returns:
 *   {declared: string[], lookalike: string[]}: the columns the graph
 *   itself declares as soft-delete evidence (authoritative), and the
 *   columns that merely LOOK like one (a question for the human).
 */
function softDeleteSignal(resource: GraphResource): { declared: string[]; lookalike: string[] } {
  const declared = attributeColumns(resource.attributes['softDeleteCandidateFields'], 'name').sort();
  if (declared.length > 0) return { declared, lookalike: [] };
  const lookalike = declaredColumns(resource).filter(
    (column) => SOFT_DELETE_COLUMNS[column.toLowerCase()] === true,
  );
  return { declared, lookalike };
}

/**
 * Renders a JS string literal for generated source.
 *
 * Args:
 *   value: the literal value.
 *
 * Returns:
 *   string: the quoted literal.
 */
function literal(value: string): string {
  return JSON.stringify(value);
}

/**
 * The header paragraph a list-only adapter carries, so the reviewer who
 * opens the file sees the cost before the code: the kit resolves every
 * member out of the complete collection, which is slower than a by-id
 * read and only correct while the collection returns every row.
 */
const LIST_ONLY_NOTICE = [
  'LIST-ONLY: the app serves no by-id route for this resource, so every read',
  'walks the COMPLETE collection and picks the member out of it. That is',
  'slower than a by-id read, and it is only correct while the collection',
  'really returns every row. Add readPath as soon as the app serves one.',
].join('\n');

/**
 * The one line that says a route EXISTS and names what actually blocks
 * it: an endpoint with no plane has no graph id, so the runtime route
 * inventory never carries it (GF-12). Reporting such a resource as
 * unserved is the false negative this replaces.
 *
 * Args:
 *   entries: the compiled routes held back by the unanswered plane.
 *
 * Returns:
 *   string: the `needs you` line.
 */
function planeBlocker(entries: readonly { route: { canonicalPath: string } }[]): string {
  const listed = entries.map((entry) => `GET ${entry.route.canonicalPath}`).sort();
  const many = listed.length > 1;
  return (
    `${listed.join(', ')} ${many ? 'exist' : 'exists'} but ` +
    `${many ? 'their' : 'its'} plane is unanswered, so the route inventory never carries ` +
    `${many ? 'them' : 'it'}: answer the plane first (\`gateforge classify plane <path>\`), then re-run`
  );
}

/**
 * Plans one adapter per business resource.
 *
 * Args:
 *   input: resources, resolved routes, plane-unanswered routes, existing
 *     adapter names, and the target fingerprint.
 *
 * Returns:
 *   ScaffoldPlan[]: one decision per resource, sorted by resource id.
 */
export function planAdapters(input: ScaffoldInput): ScaffoldPlan[] {
  const existing = new Set(input.existing);
  // Route paths no app mounts: a path derived from one of these is a
  // guess the reviewer must confirm, never a silent value.
  const unmounted = new Set(input.standalonePaths);
  const plans: ScaffoldPlan[] = [];
  for (const target of input.targets) {
    const { resource } = target;
    const resourceId = target.adapterId;
    const guesses: string[] = [];
    const needsYou: string[] = [];

    if (existing.has(resourceId)) {
      plans.push({
        resourceId,
        name: resource.name,
        status: 'exists',
        source: null,
        guesses: [],
        needsYou: [],
      });
      continue;
    }

    // Only LINKED routes may produce a file. A path that merely NAMES
    // the resource is a candidate for a human to confirm, and a route
    // the engine linked to a DIFFERENT resource is someone else's.
    const { linked, candidates } = routesForResource(resource, input.routes);
    if (linked.length > 0) {
      guesses.push(
        `routes linked to '${resource.name}' by the compiled graph (${linked
          .map((route) => `GET ${route.canonicalPath}`)
          .sort()
          .join(', ')})`,
      );
    }

    // A route with an INNER parameter is scoped to a parent: it is never
    // the complete collection of the resource, and never a by-id read of
    // the resource itself. A LITERAL segment between the resource
    // segment and the id reads something else THROUGH the resource
    // (`/shipments/carrier/{id}` looks a carrier up through a
    // shipment), so it is never the resource's own by-id read either.
    const entries = linked.map((route) => ({
      route,
      split: splitRoutePath(route.canonicalPath),
    }));
    // The same shapes, one blocker earlier: real compiled routes the
    // runtime inventory cannot carry because their plane is unanswered.
    const behindPlane = unresolvedRoutesForResource(resource, input.unresolvedRoutes).map((route) => ({
      route,
      split: splitRoutePath(route.canonicalPath),
    }));
    const literalTail = (entry: { split: { prefix: string } }): string[] =>
      literalTailAfterResource(entry.split.prefix, resource.name);
    const atOwnLevel = (entry: { split: { prefix: string } }): boolean =>
      !hasInnerParam(entry.split.prefix) && literalTail(entry).length === 0;
    const reads = entries.filter((entry) => entry.split.idSegments.length > 0 && atOwnLevel(entry));
    const collections = entries.filter(
      (entry) => entry.split.idSegments.length === 0 && atOwnLevel(entry),
    );
    const perParent = entries.filter((entry) => hasInnerParam(entry.split.prefix));
    const perParentReads = perParent.filter((entry) => entry.split.idSegments.length > 0);
    const subResourceReads = entries.filter(
      (entry) =>
        entry.split.idSegments.length > 0 &&
        !hasInnerParam(entry.split.prefix) &&
        literalTail(entry).length > 0,
    );
    const behindPlaneReads = behindPlane.filter(
      (entry) => entry.split.idSegments.length > 0 && atOwnLevel(entry),
    );
    const behindPlaneCollections = behindPlane.filter(
      (entry) => entry.split.idSegments.length === 0 && atOwnLevel(entry),
    );
    // A by-id route at the resource's OWN level that nothing linked to
    // it still counts as "the app serves a by-id read": the list-only
    // shape must not be written silently over it. A per-parent or
    // sub-resource path does not — that is not a by-id read at all.
    const unlinkedReads = candidates.filter((route) => {
      const split = splitRoutePath(route.canonicalPath);
      return (
        split.idSegments.length > 0 &&
        !hasInnerParam(split.prefix) &&
        literalTailAfterResource(split.prefix, resource.name).length === 0
      );
    });

    const softDelete = softDeleteSignal(resource);
    const singleReads = reads.filter((entry) => entry.split.idSegments.length === 1);
    const collectionFirst = collections[0];
    // One resource's read and collection share a prefix; when both are
    // derivable, prefer that pair over any other shape.
    const byId =
      singleReads.find((entry) => entry.split.prefix === collectionFirst?.split.prefix) ??
      singleReads[0];
    const composite = reads.find((entry) => entry.split.idSegments.length > 1);
    const collection =
      byId === undefined
        ? collectionFirst
        : (collections.find((entry) => entry.split.prefix === byId.split.prefix) ?? collectionFirst);
    // The kit resolves a member out of the COMPLETE collection, so a
    // resource with a collection and no by-id route at all can be
    // scaffolded as a list-only adapter. A REJECTED or unlinked by-id
    // shape is not that case: something looks like a read, and a human
    // must say which route really reads the entity.
    const listOnlyAllowed =
      byId === undefined &&
      composite === undefined &&
      behindPlaneReads.length === 0 &&
      subResourceReads.length === 0 &&
      perParentReads.length === 0 &&
      unlinkedReads.length === 0;

    if (byId === undefined && behindPlaneReads.length === 0) {
      if (subResourceReads.length > 0) {
        needsYou.push(
          `these routes add a literal segment after ${resource.name}, so they read something else ` +
            `through the resource (${subResourceReads
              .map((entry) => `GET ${entry.route.canonicalPath}`)
              .sort()
              .join(', ')}): declare readPath yourself — a sub-resource path is never a by-id read`,
        );
      } else if (perParentReads.length > 0) {
        needsYou.push(
          `every by-id route for ${resource.name} is a per-parent route (${perParentReads
            .map((entry) => `GET ${entry.route.canonicalPath}`)
            .sort()
            .join(', ')}): a per-parent read is not a by-id read of the resource — declare ` +
            'readPath yourself',
        );
      } else {
        needsYou.push(
          composite === undefined
            ? `no GET route serves one ${resource.name} entity: declare readPath yourself — the ` +
              'adapter cannot read an entity without one'
            : `the by-id route serves a COMPOSITE key ` +
              `(${composite.split.idSegments.join(', ')}): declare readPath as a function of the ` +
              'composite key yourself',
        );
      }
    }
    if (collection === undefined && behindPlaneCollections.length === 0) {
      const perParentCollections = perParent.filter((entry) => entry.split.idSegments.length === 0);
      needsYou.push(
        perParentCollections.length > 0
          ? `only per-parent collections serve ${resource.name} (${perParentCollections
              .map((entry) => `GET ${entry.route.canonicalPath}`)
              .sort()
              .join(', ')}): a sub-collection is never the complete collection — declare ` +
            'listPath / listCollection yourself'
          : `no GET collection route serves ${resource.name}: a create cannot be witnessed without a ` +
            'complete collection read (ADAPTER_CANNOT_WITNESS) — declare listPath yourself',
      );
    }
    if (input.environmentFingerprint === null) {
      needsYou.push(
        'the target environment fingerprint is unknown: export GATEFORGE_TARGET_FINGERPRINT (the ' +
          'value the app presents in the x-gateforge-env-fingerprint header) and re-run',
      );
    }
    // A path that merely NAMES the resource is never turned into a
    // written readPath: the candidates are listed so a human can say
    // which route serves the entity (GF-18).
    if (candidates.length > 0 && byId === undefined) {
      needsYou.push(
        `nothing is written from a name match: no schema or handler evidence links a by-id route to ` +
          `${resource.name}, so the scaffolder will not turn one of these into a readPath — ` +
          `confirm which serves the entity: ${candidates
            .map((route) => `GET ${route.canonicalPath}`)
            .sort()
            .join(', ')}. Then link it (or declare readPath / listPath yourself)`,
      );
    }
    if (
      target.deleteSemantics === null &&
      softDelete.declared.length === 0 &&
      softDelete.lookalike.length > 0
    ) {
      needsYou.push(
        `table has ${softDelete.lookalike.join(', ')}: if DELETE archives instead of removing, set ` +
          "deletion: 'archive' — the graph declares no delete semantics, so the generated value is a " +
          'guess',
      );
    }
    if (byId !== undefined || collection !== undefined) {
      needsYou.push(
        'reads may need authentication: if the app answers 401, declare auth.seats with the ' +
          'witness environment variables holding the credentials',
      );
    }

    // A file is written when the kit can observe the resource at all:
    // through a by-id read, or (a list-only adapter) through the
    // complete collection when the app genuinely serves no by-id route.
    if (
      input.environmentFingerprint === null ||
      collection === undefined ||
      (byId === undefined && !listOnlyAllowed)
    ) {
      if (behindPlane.length > 0) {
        needsYou.unshift(planeBlocker(behindPlane));
      }
      plans.push({
        resourceId,
        name: resource.name,
        status: 'needs-you',
        source: null,
        guesses,
        needsYou,
      });
      continue;
    }

    const readPath = byId === undefined ? null : byId.split.prefix + '/{id}';
    const listOnly = readPath === null;
    const listPath = collection.route.canonicalPath;
    const { fields, excluded } = projectedFields(resource);
    if (fields.length === 0) {
      needsYou.push(
        `the graph declares no columns for ${resource.name} beyond its primary key and secrets: add the ` +
          'business fields the obligations grade — a response-only computed field is the human’s call',
      );
    }
    const deletion = target.deleteSemantics ?? (softDelete.declared.length > 0 ? 'archive' : 'hard');
    if (byId !== undefined) {
      guesses.push(`readPath '${byId.split.prefix}/{id}' guessed from GET ${byId.route.canonicalPath}`);
    }
    for (const [role, source] of [
      ...(byId === undefined ? [] : [['readPath', byId.route.canonicalPath] as const]),
      ['listPath', collection.route.canonicalPath] as const,
    ]) {
      if (!unmounted.has(source)) continue;
      guesses.push(
        `${role} taken from GET ${source}, which no app mounts (the router is never included): the ` +
          'route exists in the source tree but nothing serves it — confirm it before trusting this path',
      );
      needsYou.push(
        `GET ${source} is declared by a router no app mounts: the generated ${role} points at a ` +
          'route nothing serves — confirm the path, or declare the mounted one yourself',
      );
    }
    if (readPath === null) {
      guesses.push(
        `readPath omitted: no linked GET route serves one ${resource.name} entity, so the kit ` +
          'resolves each member out of the complete collection — add readPath as soon as the app ' +
          'serves a by-id route',
      );
    }
    guesses.push(`listPath '${listPath}' guessed from GET ${collection.route.canonicalPath}`);
    guesses.push(
      'collectionKey guessed as the first array in the response body — replace it with the exact key',
    );
    guesses.push(`paging guessed as page/page_size (a single page would hide rows behind page 1)`);
    guesses.push(
      fields.length === 0
        ? 'no fields could be derived; add the business fields the obligations grade'
        : `fields [${fields.join(', ')}] derived from every column the compiled graph declares for ` +
          `${resource.name}` +
          (excluded.length === 0 ? '' : ` (excluded: ${excluded.join(', ')})`),
    );
    guesses.push('itemWrapper guessed as none (the response body IS the entity)');
    guesses.push(
      target.deleteSemantics !== null
        ? `deletion '${deletion}' taken from the classification's delete semantics`
        : softDelete.declared.length > 0
          ? `deletion '${deletion}' taken from the graph's soft-delete signal (${softDelete.declared.join(', ')}), ` +
            'which is a guess about the endpoint: confirm the endpoint archives the row'
          : softDelete.lookalike.length > 0
            ? `deletion '${deletion}' GUESSED: the table has ${softDelete.lookalike.join(', ')}, ` +
              'which usually means a soft delete — confirm whether the endpoint hard-deletes or archives'
            : `deletion '${deletion}' GUESSED: the classifier could not prove the delete semantics, so ` +
              'confirm whether the resource hard-deletes or archives',
    );
    guesses.push(
      'environmentFingerprint taken from GATEFORGE_TARGET_FINGERPRINT (the run target marker)',
    );

    const source = [
      guessComment(resourceId, guesses, listOnly ? LIST_ONLY_NOTICE : undefined),
      '',
      "import { defineHttpAdapter, firstArrayOf } from '@gate-forge/witness/adapter-kit';",
      '',
      'export default defineHttpAdapter({',
      `  resourceId: ${literal(resourceId)},`,
      ...(readPath === null ? [] : [`  readPath: ${literal(readPath)},`]),
      `  listPath: ${literal(listPath)},`,
      '  collectionKey: firstArrayOf,',
      '  paging: { kind: \'page\', pageSize: 100 },',
      `  fields: [${fields.map((field) => literal(field)).join(', ')}],`,
      `  deletion: ${literal(deletion)},`,
      `  environmentFingerprint: ${literal(input.environmentFingerprint)},`,
      '});',
      '',
    ].join('\n');
    plans.push({ resourceId, name: resource.name, status: 'create', source, guesses, needsYou });
  }
  return plans.sort((a, b) => (a.resourceId < b.resourceId ? -1 : a.resourceId > b.resourceId ? 1 : 0));
}
