/**
 * The WITNESSED CI job template (managed-run plan, Part C, feedback E59).
 *
 * `gateforge enforce --ci gitlab|github --witnessed` writes this file
 * NEXT TO the static one. A consumer used to hand-write the whole
 * witnessed lane — job-scoped stack/image names, a private workspace,
 * merge-request base-sha forwarding, verdict extraction, artifacts —
 * and the second consumer would have written it again. The generated job
 * is plain reviewable YAML; nothing runs at generation time.
 *
 * The app owns its own lifecycle: `.gateforge/runtime.yml` resets,
 * seeds and starts the services, and `gateforge run` sequences recipe
 * -> supervised suite -> strict check. The consumer fills the recipe and
 * the secret variables, and nothing else.
 */
import { existsSync, mkdirSync, readFileSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import type { Io } from './io.js';
import { recordInitPath, writeLine } from './io.js';
import { CI_INSTALL_SCRIPT, ciScriptBlock } from './commands/blocking.js';
import { VERSION } from './commands/common.js';

/** Job name of the generated GitLab witnessed job. */
export const GITLAB_WITNESSED_JOB = 'gateforge:witnessed';
/** Job id of the generated GitHub Actions witnessed job. */
export const GITHUB_WITNESSED_JOB = 'witnessed';
/** Repo-relative path of the generated GitLab witnessed job. */
export const GITLAB_WITNESSED_PATH = '.gateforge/ci/gitlab-witnessed.yml';
/** Repo-relative path of the generated GitHub Actions witnessed job. */
export const GITHUB_WITNESSED_PATH = '.github/workflows/gateforge-witnessed.yml';

/**
 * The job-scoped shell block: private workspace, base-sha forwarding
 * into BOTH supervised commands, and the managed run. The run prints
 * straight into the job log, so the progress stream (on by default
 * under CI=true) is visible while the suite runs. Nothing captures that
 * output into a file: the suite's own output passes through it and may
 * carry the app's secrets, so it must never become an artifact.
 * Unindented, so each provider indents it into its own YAML.
 */
const WITNESSED_RUN_SCRIPT: readonly string[] = [
  'set -eu',
  '# The job owns a private, job-scoped workspace and names. Nothing two',
  '# concurrent jobs of one project share, and nothing a later job can',
  '# find by accident. The app recipe may use them (stack, volumes).',
  'mkdir -p "$GATEFORGE_CI_WORKSPACE" .gateforge/test-gates',
  '# Forward the merge-request base sha to the scope provider of BOTH',
  '# supervised commands: `gateforge run` executes test-gates and',
  '# `check --require-e2e` in this environment. Without it the provider',
  '# falls back to a local diff that can select zero changed files.',
  'if [ -n "${CI_MERGE_REQUEST_DIFF_BASE_SHA:-}" ]; then',
  '  export CI_MERGE_REQUEST_DIFF_BASE_SHA',
  '  export GATEFORGE_CI_BASE_SHA="$CI_MERGE_REQUEST_DIFF_BASE_SHA"',
  'fi',
  "# The app lifecycle lives in .gateforge/runtime.yml (reset, seed,",
  '# services, teardown). Full scope is the default: narrowing the run',
  "# is the owner's edit, not the template's.",
  'if run_gateforge run -- --changed --scope full; then',
  '  run_status=0',
  'else',
  '  run_status=$?',
  'fi',
];

/**
 * The verdict block: the counts come from the report json, never from a
 * parsed log line, and no secret variable is ever printed.
 */
const WITNESSED_VERDICT_SCRIPT: readonly string[] = [
  'if [ -f .gateforge/test-gates/report.json ]; then',
  '  node -e \'const fs=require("node:fs");const report=JSON.parse(fs.readFileSync(".gateforge/test-gates/report.json","utf8"));const summary=report.summary||{};console.log("Gateforge CI: verdict "+String(summary.satisfied)+" satisfied, "+String(summary.waived)+" waived, "+String(summary.blocking)+" blocking of "+String(summary.obligations)+" obligations (scope "+String((report.scope||{}).mode)+")");for(const entry of (report.blocking||[]).slice(0,20)){console.log("Gateforge CI: blocking "+entry.kind+": "+(entry.detail||""))}\'',
  'else',
  '  echo "Gateforge CI: no report.json — the run failed before it wrote one" >&2',
  '  run_status=1',
  'fi',
  'exit "$run_status"',
];

/**
 * Renders the witnessed GitLab CI job.
 *
 * Args:
 *   none.
 *
 * Returns:
 *   string: the include-able job definition.
 */
export function renderGitlabWitnessedTemplate(): string {
  return `# Generated by Gateforge ${VERSION}; the witnessed lane. Review before enabling it.
# One job, one proof: \`gateforge run\` sequences the app's own recipe
# (.gateforge/runtime.yml), the supervised suite and the strict check, and
# the engine seals the receipt this job uploads. Nothing here interprets
# the app's stack — that is the recipe's job.
#
# Secret variables come from protected, masked CI variables; this job
# never prints one. Neither the recipe log (.gateforge/test-gates/run-recipe/)
# nor the suite's raw output is an artifact: both may contain the app's own
# secrets. failures.json is the secret-screened failure diagnosis.
#
# GATEFORGE_WITNESS_VERIFIER_KEY and GATEFORGE_APPROVED_POLICY_DIGEST are
# required; \`gateforge run\` fails preflight and names the missing one.
${GITLAB_WITNESSED_JOB}:
  stage: test
  image: node:22
  variables:
    GATEFORGE_VERSION: "${VERSION}"
    GATEFORGE_CI_NESTED_PACKAGE_DIRS: ""
    GATEFORGE_CI_JOB_SCOPE: "\${CI_PROJECT_PATH_SLUG}-\${CI_JOB_ID}"
    GATEFORGE_CI_STACK_NAME: "\${CI_PROJECT_PATH_SLUG}-witnessed-\${CI_JOB_ID}"
    GATEFORGE_CI_IMAGE_NAME: "\${CI_PROJECT_PATH_SLUG}-witnessed-\${CI_JOB_ID}:\${CI_COMMIT_SHORT_SHA}"
    GATEFORGE_CI_WORKSPACE: "\${CI_PROJECT_DIR}/.gateforge/ci-witnessed/\${CI_JOB_ID}"
  script:
    - |
${ciScriptBlock(CI_INSTALL_SCRIPT)}
    - |
${ciScriptBlock(WITNESSED_RUN_SCRIPT)}
    - |
${ciScriptBlock(WITNESSED_VERDICT_SCRIPT)}
  artifacts:
    when: always
    paths:
      - .gateforge/test-gates/report.json
      - .gateforge/test-gates/receipt.json
      - .gateforge/test-gates/execution-result.json
      - .gateforge/test-gates/failures.json
    expire_in: 90 days
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
    - if: $CI_PIPELINE_SOURCE == "push" && $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
`;
}

/**
 * Renders the witnessed GitHub Actions workflow. Secrets arrive as
 * environment values on the run step and are never echoed.
 *
 * Args:
 *   none.
 *
 * Returns:
 *   string: the workflow source.
 */
export function renderGithubWitnessedTemplate(): string {
  return `# Generated by Gateforge ${VERSION}; the witnessed lane. Review before enabling it.
name: Gateforge witnessed
on:
  pull_request:
  push:
  workflow_dispatch:
permissions:
  contents: read
jobs:
  ${GITHUB_WITNESSED_JOB}:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v4
        with:
          node-version: 22
      - name: Install Gateforge
        run: npm install --no-save --package-lock=false @gate-forge/cli@${VERSION}
      - name: Job-scoped names and workspace
        run: |
          set -eu
          echo "GATEFORGE_CI_JOB_SCOPE=\${{ github.repository }}-\${{ github.run_id }}-\${{ github.run_attempt }}" >> "\$GITHUB_ENV"
          echo "GATEFORGE_CI_WORKSPACE=\${{ github.workspace }}/.gateforge/ci-witnessed/\${{ github.run_id }}-\${{ github.run_attempt }}" >> "\$GITHUB_ENV"
          mkdir -p "\$GITHUB_WORKSPACE/.gateforge/test-gates"
      - name: Forward the pull-request base ref
        if: github.event_name == 'pull_request'
        run: |
          set -eu
          # The scope provider diffs against the merge base of the base
          # branch, and it must be a real local ref: export the remote
          # tracking ref plus the merge-base sha for the run.
          git fetch --no-tags --quiet origin "\${{ github.base_ref }}:refs/remotes/origin/\${{ github.base_ref }}"
          echo "GITHUB_BASE_REF=refs/remotes/origin/\${{ github.base_ref }}" >> "\$GITHUB_ENV"
          echo "GATEFORGE_CI_BASE_SHA=\$(git merge-base HEAD "refs/remotes/origin/\${{ github.base_ref }}")" >> "\$GITHUB_ENV"
      - name: Witnessed run
        env:
          GATEFORGE_WITNESS_VERIFIER_KEY: \${{ secrets.GATEFORGE_WITNESS_VERIFIER_KEY }}
          GATEFORGE_APPROVED_POLICY_DIGEST: \${{ secrets.GATEFORGE_APPROVED_POLICY_DIGEST }}
        run: |
          set -eu
          # \`gateforge run\` sequences the app's own recipe
          # (.gateforge/runtime.yml), the supervised suite and the strict
          # check. Full scope is the default: narrowing the run is the
          # owner's edit, not the template's.
          run_status=0
          ./node_modules/.bin/gateforge run -- --changed --scope full || run_status=$?
          if [ -f .gateforge/test-gates/report.json ]; then
            node -e 'const fs=require("node:fs");const report=JSON.parse(fs.readFileSync(".gateforge/test-gates/report.json","utf8"));const summary=report.summary||{};console.log("Gateforge CI: verdict "+String(summary.satisfied)+" satisfied, "+String(summary.waived)+" waived, "+String(summary.blocking)+" blocking of "+String(summary.obligations)+" obligations (scope "+String((report.scope||{}).mode)+")");for(const entry of (report.blocking||[]).slice(0,20)){console.log("::error::"+entry.kind+": "+(entry.detail||""))}'
          else
            echo "Gateforge CI: no report.json — the run failed before it wrote one" >&2
            run_status=1
          fi
          exit "$run_status"
      - name: Upload the witnessed evidence
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: gateforge-witnessed
          # Neither the recipe log (.gateforge/test-gates/run-recipe/) nor
          # the suite's raw output is uploaded: both may contain the app's
          # own secrets. failures.json is the secret-screened diagnosis.
          path: |
            .gateforge/test-gates/report.json
            .gateforge/test-gates/receipt.json
            .gateforge/test-gates/execution-result.json
            .gateforge/test-gates/failures.json
          if-no-files-found: warn
          retention-days: 90
`;
}

/**
 * Writes one generated file only when it is absent — the same
 * no-overwrite rule the static generator follows.
 *
 * Args:
 *   io: process context.
 *   path: absolute target path.
 *   content: the file to write when absent.
 *
 * Returns:
 *   void.
 */
function writeGenerated(io: Io, path: string, content: string): void {
  if (existsSync(path)) {
    recordInitPath(io, io.cwd, path, 'preserved');
    writeLine(io.stdout, `exists, leaving untouched: ${path}`);
    return;
  }
  mkdirSync(dirname(path), { recursive: true });
  writeFileSync(path, content, 'utf8');
  recordInitPath(io, io.cwd, path, 'created');
  writeLine(io.stdout, `created: ${path}`);
}

/**
 * Adds the local include of the witnessed job to `.gitlab-ci.yml`,
 * never rewriting an include the owner already wrote.
 *
 * Args:
 *   io: process context.
 *
 * Returns:
 *   void.
 */
function ensureGitlabInclude(io: Io): void {
  const path = join(io.cwd, '.gitlab-ci.yml');
  const local = `  - local: '${GITLAB_WITNESSED_PATH}'`;
  if (!existsSync(path)) {
    writeFileSync(path, `include:\n${local}\n`);
    recordInitPath(io, io.cwd, path, 'created');
    writeLine(io.stdout, `created: ${path} (includes the gateforge witnessed job)`);
    return;
  }
  const current = readFileSync(path, 'utf8');
  if (current.includes(GITLAB_WITNESSED_PATH)) {
    recordInitPath(io, io.cwd, path, 'preserved');
    writeLine(io.stdout, `exists, leaving untouched: ${path} (witnessed include present)`);
    return;
  }
  const updated = /^include:/m.test(current)
    ? current.replace(/^include:[^\n]*/m, (match) => `${match}\n${local}`)
    : `${current.endsWith('\n') ? current : `${current}\n`}include:\n${local}\n`;
  writeFileSync(path, updated, 'utf8');
  writeLine(io.stdout, `updated: ${path} (witnessed include added)`);
}

/**
 * Writes the witnessed job template for the selected provider, plus the
 * provider's include wiring. Plain files: the owner reviews them.
 *
 * Args:
 *   io: process context.
 *   provider: GitHub Actions or GitLab CI.
 *
 * Returns:
 *   void.
 */
export function writeWitnessedCiTemplate(io: Io, provider: 'github' | 'gitlab'): void {
  if (provider === 'github') {
    writeGenerated(io, join(io.cwd, GITHUB_WITNESSED_PATH), renderGithubWitnessedTemplate());
    return;
  }
  writeGenerated(io, join(io.cwd, GITLAB_WITNESSED_PATH), renderGitlabWitnessedTemplate());
  ensureGitlabInclude(io);
}
