/**
 * Gateforge-owned policy inputs (0.9.0 D2).
 *
 * These are the files Gateforge itself writes and reads when it configures
 * and wires itself: the config document, the policy / classification /
 * behavior / runtime documents, the pack configs, the adapter, waiver,
 * baseline and quarantine records, the generated gate wiring (hook script,
 * CI job templates, agent skill file, engine reference) and the owner's own
 * CI / pre-commit files while they still carry Gateforge's managed block.
 *
 * A change to one of them is a POLICY INPUT, never a product change:
 *
 * - it is never reported as an unmapped (`CHANGE_UNMAPPED`) product change,
 *   because nothing about product behavior is unaccounted for;
 * - its integrity stays governed by the owner-approved policy digest exactly
 *   as it is today — `computeTrustedPolicyDigest` hashes the config, policy,
 *   classification, behavior, runtime, mapping-sidecar,
 *   adapter, waiver, quarantine and repo-local plugin bytes, so a candidate
 *   that changes any of them changes the approved revision and a pin mismatch
 *   still blocks;
 * - a change set whose ENTIRE content is these paths cannot change product
 *   behavior, so it does not drag the adopted E2E obligations into a strict
 *   re-grade (the adoption forgiveness survives; an owner waiver does not).
 *
 * Security boundary — the set is EXACT, never a directory wildcard:
 *
 * - `.gateforge/` is NOT exempt as a tree. Only the engine documents at its
 *   top level and the engine-owned subdirectories are, so an agent cannot
 *   park a product change somewhere under `.gateforge/` and have it excused.
 *   Engine run state (`.gateforge/test-gates/`, `.gateforge/ci-witnessed/`)
 *   stays outside the set on purpose: staged engine state is not a policy
 *   input and stays visible.
 * - The owner's CI config and pre-commit config count ONLY while Gateforge's
 *   managed block is still in them. Deleting the gate job from
 *   `.gitlab-ci.yml` therefore keeps its historical, blocking
 *   `CHANGE_UNMAPPED` treatment.
 */
import { existsSync, readFileSync } from 'node:fs';
import { join } from 'node:path';
import type { GateforgeConfig } from '@gate-forge/core';
import { PACK_CONFIGS, normalizeRepoModule } from './input-snapshot.js';
import { DEFAULT_STATE_DIR } from './state.js';

/** Repo-relative path of the tracked mapping sidecar. */
export const GATEFORGE_TEST_MAP_PATH = '.gateforge/test-map.yml';

/** Repo-relative path of the machine-specific engine checkout reference. */
export const GATEFORGE_ENGINE_REFERENCE_PATH = '.gateforge/engine';

/** Repo-relative path of the agent skill file `init` writes. */
export const GATEFORGE_SKILL_FILE = 'GATEFORGE.md';

/**
 * Repo-relative path of the overlay-proof directory README `init` writes.
 * EXACT path on purpose: the overlay TESTS an owner or agent writes beside
 * it in `tests/e2e/gateforge/` are product work and stay mappable and
 * gradeable.
 */
export const GATEFORGE_OVERLAY_README_PATH = 'tests/e2e/gateforge/README.md';

/**
 * The comment line that introduces Gateforge's managed
 * `.gitignore` block. ONE definition shared by the writer
 * (`init`) and the classifier (this module), so the block
 * `init` appends is exactly the block the classifier
 * recognizes.
 */
export const ENGINE_STATE_IGNORE_COMMENT =
  '# Gateforge engine state — never committed (regenerated by every run).';

/**
 * The engine-owned state directories that must never be
 * committed (`.gateforge/test-gates/` — the run catalog,
 * plugin caches, receipts and history the engine regenerates
 * on every run). ONE definition shared by the writer (`init`)
 * and the classifier (this module).
 */
export const ENGINE_STATE_IGNORE_ENTRIES: readonly string[] = [
  `${DEFAULT_STATE_DIR}/`,
];

/**
 * Engine-owned subdirectories of `.gateforge/`: the generated gate wiring and
 * the record directories every gate decision reads. Segment-aware matching
 * only — `.gateforge/hooksy/x` is not inside `.gateforge/hooks`.
 */
export const GATEFORGE_OWNED_DIRS: readonly string[] = [
  '.gateforge/adapters',
  '.gateforge/baselines',
  '.gateforge/ci',
  '.gateforge/hooks',
  '.gateforge/quarantine',
  '.gateforge/waivers',
];

/**
 * Extensions accepted for an engine document directly under `.gateforge/`
 * (`.gateforge/policies.yml`, `.gateforge/planes.json`, …). Source and
 * executable code never qualifies: only documents the engine itself reads.
 */
const ENGINE_DOCUMENT_EXTENSIONS: ReadonlySet<string> = new Set([
  '.yml',
  '.yaml',
  '.json',
  '.md',
  '.txt',
]);

/**
 * Owner-owned files that carry a Gateforge-managed block, with the markers
 * that prove the block is still wired. A file whose marker is gone is not a
 * policy input anymore — that is exactly the E17 self-authorization case.
 */
const MANAGED_OWNER_FILES: Readonly<Record<string, { kind: GateforgeOwnedInputKind; markers: readonly string[] }>> = {
  '.gitlab-ci.yml': { kind: 'ci-wiring', markers: ['.gateforge/ci/'] },
  '.pre-commit-config.yaml': { kind: 'pre-commit-wiring', markers: ['gateforge-check'] },
  '.github/workflows/gateforge.yml': { kind: 'ci-wiring', markers: ['# Generated by Gateforge'] },
  '.github/workflows/gateforge-witnessed.yml': { kind: 'ci-wiring', markers: ['# Generated by Gateforge'] },
};

/** What kind of Gateforge-owned input a path is. */
export type GateforgeOwnedInputKind =
  | 'config'
  | 'policy'
  | 'classification-policy'
  | 'behavior-policy'
  | 'runtime-policy'
  | 'mapping-sidecar'
  | 'pack-config'
  | 'adapter'
  | 'waiver'
  | 'baseline'
  | 'quarantine'
  | 'plugin-module'
  | 'wiring'
  | 'engine-reference'
  | 'agent-skill'
  | 'ci-wiring'
  | 'ignore-wiring'
  | 'pre-commit-wiring';

/** One Gateforge-owned policy input: the matched path and what it is. */
export interface GateforgeOwnedInput {
  /** Repo-relative posix path that was matched (the file or its directory). */
  readonly path: string;
  /** Stable class label, printed by `gateforge explain`. */
  readonly kind: GateforgeOwnedInputKind;
}

/** Normalizes a configured repo path to the posix form used for comparison. */
function normalizeRepoPath(path: string): string {
  const posix = path.split('\\').join('/');
  return posix.startsWith('./') ? posix.slice(2) : posix;
}

/** Segment-aware directory membership (`a/b` is inside `a`, `a2` is not). */
function underDir(file: string, dir: string): boolean {
  return file === dir || file.startsWith(`${dir}/`);
}

/** The lowercase extension of a basename, or `''` when it has none. */
function extensionOf(basename: string): string {
  const lower = basename.toLowerCase();
  return lower.includes('.') ? lower.slice(lower.lastIndexOf('.')) : '';
}

/**
 * Classifies a repo-relative path as a Gateforge-owned policy input.
 *
 * Args:
 *   file: normalized repo-relative changed path.
 *   config: the loaded gateforge config (its document paths are honored).
 *
 * Returns:
 *   GateforgeOwnedInput | null: the matched input, or null when the path is
 *   not a Gateforge-owned policy input (a product file, or engine run state).
 */
export function gateforgeOwnedInput(file: string, config: GateforgeConfig): GateforgeOwnedInput | null {
  const posix = normalizeRepoPath(file);
  if (posix === '.gateforge.yml') return { path: '.gateforge.yml', kind: 'config' };
  if (posix === GATEFORGE_SKILL_FILE) return { path: GATEFORGE_SKILL_FILE, kind: 'agent-skill' };
  if (posix === GATEFORGE_OVERLAY_README_PATH) {
    return { path: GATEFORGE_OVERLAY_README_PATH, kind: 'agent-skill' };
  }
  if (posix === GATEFORGE_ENGINE_REFERENCE_PATH) {
    return { path: GATEFORGE_ENGINE_REFERENCE_PATH, kind: 'engine-reference' };
  }
  if (posix === GATEFORGE_TEST_MAP_PATH) return { path: GATEFORGE_TEST_MAP_PATH, kind: 'mapping-sidecar' };
  for (const packConfig of PACK_CONFIGS) {
    if (posix === packConfig) return { path: packConfig, kind: 'pack-config' };
  }
  // Configured documents: the config may point anywhere in the repository.
  if (posix === normalizeRepoPath(config.policies)) return { path: posix, kind: 'policy' };
  if (posix === normalizeRepoPath(config.classificationPolicy)) {
    return { path: posix, kind: 'classification-policy' };
  }
  if (config.behaviorPolicy !== undefined && posix === normalizeRepoPath(config.behaviorPolicy)) {
    return { path: posix, kind: 'behavior-policy' };
  }
  if (config.runtime !== undefined && posix === normalizeRepoPath(config.runtime)) {
    return { path: posix, kind: 'runtime-policy' };
  }
  const baselines = normalizeRepoPath(config.baselines);
  if (posix === baselines) return { path: posix, kind: 'baseline' };
  const adapters = normalizeRepoPath(config.adapters);
  if (underDir(posix, adapters)) return { path: adapters, kind: 'adapter' };
  const waivers = normalizeRepoPath(config.waivers);
  if (underDir(posix, waivers)) return { path: waivers, kind: 'waiver' };
  for (const plugin of config.plugins) {
    const module = plugin.module;
    if (typeof module !== 'string') continue;
    const normalized = normalizeRepoModule(module);
    if (normalized !== null && (posix === normalized || underDir(posix, normalized))) {
      return { path: normalized, kind: 'plugin-module' };
    }
  }
  // The baseline record directory: the adoption receipt is the sibling of the
  // configured baseline document and Gateforge writes both.
  const baselineDir = baselines.slice(0, baselines.lastIndexOf('/'));
  if (baselineDir.includes('/') && underDir(posix, baselineDir)) return { path: baselineDir, kind: 'baseline' };
  for (const dir of GATEFORGE_OWNED_DIRS) {
    if (underDir(posix, dir)) return { path: dir, kind: dir === '.gateforge/quarantine' ? 'quarantine' : 'wiring' };
  }
  // Engine documents directly under `.gateforge/` (`runtime.yml`, a custom
  // policies document, …). Depth one only, and only document types —
  // `.gateforge/<anything>.py` is not a policy input. (The 0.9 evidence
  // exclusion declarations were here too; they are refused by name since
  // 0.10 and migrate into `.gateforge.yml`.)
  const segments = posix.split('/');
  if (
    segments.length === 2 &&
    segments[0] === '.gateforge' &&
    ENGINE_DOCUMENT_EXTENSIONS.has(extensionOf(segments[1] ?? ''))
  ) {
    return { path: posix, kind: 'policy' };
  }
  return null;
}

/**
 * Whether an owner-owned file still carries Gateforge's managed block.
 *
 * Args:
 *   cwd: absolute repo root (the candidate's own checkout).
 *   file: repo-relative path.
 *
 * Returns:
 *   boolean: true for a managed owner file whose marker is still present.
 */
export function managedOwnerBlockPresent(cwd: string, file: string): boolean {
  const entry = MANAGED_OWNER_FILES[file];
  if (entry === undefined) return false;
  const absolute = join(cwd, ...file.split('/'));
  if (!existsSync(absolute)) return false;
  try {
    const body = readFileSync(absolute, 'utf8');
    return entry.markers.some((marker) => body.includes(marker));
  } catch {
    return false;
  }
}

/** Repo-relative path of the ignore file `init` wires its managed block into. */
const GITIGNORE_PATH = '.gitignore';

/**
 * Whether one `.gitignore` line belongs to Gateforge's
 * managed engine-state block: the comment line that
 * introduces it, or one of the ignored engine-state
 * entries.
 *
 * Args:
 *   line: one `.gitignore` line.
 *
 * Returns:
 *   boolean: true for a managed-block line.
 */
function isEngineStateIgnoreLine(line: string): boolean {
  return (
    line === ENGINE_STATE_IGNORE_COMMENT ||
    ENGINE_STATE_IGNORE_ENTRIES.includes(line)
  );
}

/**
 * The lines of a `.gitignore`, normalized for the
 * managed-block comparison: split on `\n`, dropping a
 * trailing empty line.
 *
 * Args:
 *   text: the full `.gitignore` contents.
 *
 * Returns:
 *   string[]: the normalized lines.
 */
function ignoreLines(text: string): string[] {
  const lines = text.split('\n');
  if (lines.length > 0 && lines[lines.length - 1] === '') {
    lines.pop();
  }
  return lines;
}

/**
 * Classifies `.gitignore` as a Gateforge-owned input (kind
 * `ignore-wiring`) when the managed engine-state block is
 * the ONLY difference from the base revision of the change
 * set: `init` appends exactly that block while writing the
 * skeleton, so a setup commit that stages it is
 * product-behavior-neutral and keeps the adopted E2E debt
 * forgiven under strictE2E.
 *
 * Security boundary — exact line equality only. The
 * candidate must actually carry the managed block, the
 * base text must exist, and every other line must be
 * unchanged: a `.gitignore` that is absent at the base
 * revision, or that adds, removes or changes any other
 * line, is NOT owned, because ignore wiring can hide
 * product changes from the scan.
 *
 * Args:
 *   cwd: absolute repo root (the candidate's own checkout).
 *   baseText: reads a repo path at the base revision of
 *     the change set (null when absent there).
 *
 * Returns:
 *   GateforgeOwnedInput | null: the owned input, or null.
 */
function ignoreWiringInput(
  cwd: string,
  baseText: (path: string) => string | null,
): GateforgeOwnedInput | null {
  const base = baseText(GITIGNORE_PATH);
  if (base === null) return null;
  let candidate: string;
  try {
    candidate = readFileSync(join(cwd, ...GITIGNORE_PATH.split('/')), 'utf8');
  } catch {
    return null;
  }
  const candidateLines = ignoreLines(candidate);
  if (!candidateLines.some((line) => isEngineStateIgnoreLine(line))) {
    return null;
  }
  const strippedCandidate = candidateLines.filter(
    (line) => !isEngineStateIgnoreLine(line),
  );
  const strippedBase = ignoreLines(base).filter(
    (line) => !isEngineStateIgnoreLine(line),
  );
  if (strippedCandidate.length !== strippedBase.length) return null;
  for (const [index, line] of strippedCandidate.entries()) {
    if (line !== strippedBase[index]) return null;
  }
  return { path: GITIGNORE_PATH, kind: 'ignore-wiring' };
}

/**
 * Classifies a path including the owner files that carry a
 * managed block, and `.gitignore` while the managed
 * engine-state block is the sole difference from the base
 * revision.
 *
 * Args:
 *   cwd: absolute repo root (the candidate's own checkout).
 *   file: repo-relative path.
 *   config: the loaded gateforge config.
 *   baseText: reads a repo path at the base revision of the
 *     change set (null when absent there); without it no
 *     `.gitignore` is ever owned.
 *
 * Returns:
 *   GateforgeOwnedInput | null: the matched input, or null.
 */
export function classifyGateforgeOwnedInput(
  cwd: string,
  file: string,
  config: GateforgeConfig,
  baseText?: (path: string) => string | null,
): GateforgeOwnedInput | null {
  const direct = gateforgeOwnedInput(file, config);
  if (direct !== null) return direct;
  const posix = normalizeRepoPath(file);
  const managed = MANAGED_OWNER_FILES[posix];
  if (managed !== undefined) {
    return managedOwnerBlockPresent(cwd, posix)
      ? { path: posix, kind: managed.kind }
      : null;
  }
  if (posix === GITIGNORE_PATH && baseText !== undefined) {
    return ignoreWiringInput(cwd, baseText);
  }
  return null;
}

/**
 * Classifies a whole changed set in one pass (one config walk, no re-reads
 * per file beyond the managed-block and `.gitignore` checks).
 *
 * Args:
 *   cwd: absolute repo root.
 *   files: repo-relative changed paths.
 *   config: the loaded gateforge config.
 *   baseText: reads a repo path at the base revision of the
 *     change set (null when absent there); without it no
 *     `.gitignore` is ever owned.
 *
 * Returns:
 *   Map<string, GateforgeOwnedInput>: the subset that is Gateforge-owned.
 */
export function gateforgeOwnedInputs(
  cwd: string,
  files: readonly string[],
  config: GateforgeConfig,
  baseText?: (path: string) => string | null,
): Map<string, GateforgeOwnedInput> {
  const owned = new Map<string, GateforgeOwnedInput>();
  for (const file of files) {
    const match = classifyGateforgeOwnedInput(cwd, file, config, baseText);
    if (match !== null) owned.set(file, match);
  }
  return owned;
}