/**
 * Active commit-hook installation and inspection (plan 2026-09-13
 * Phase 5 item 1, ADR 0005 D1): `init --blocking` installs AND verifies
 * an ACTIVE pre-commit hook in the repository's resolved hooks directory
 * (`git rev-parse --git-path hooks` honors `core.hooksPath`), it does not
 * merely write a configuration file.
 *
 * Safety rules:
 * - IDEMPOTENT: a hook carrying the gateforge marker block is verified
 *   (exec bit + verified `--gateforge-verify` invocation), never
 *   rewritten.
 * - PRESERVING: a non-gateforge pre-commit hook is NEVER clobbered — the
 *   install refuses with the exact chaining action (source the
 *   gateforge staged-gate script from the existing hook) and reports the
 *   installation incomplete (typed, nonzero exit at the caller).
 * - FAIL-CLOSED: when activation cannot be completed safely (not a repo,
 *   unwritable hooks dir, verification failure) the caller receives a
 *   typed incomplete-installation outcome naming the exact required
 *   action — never a silently inactive gate.
 */
import { chmodSync, existsSync, mkdirSync, readFileSync, statSync, writeFileSync } from 'node:fs';
import { spawnSync } from 'node:child_process';
import { join } from 'node:path';
import { HOOK_MARKER_BEGIN, HOOK_MARKER_END, HOOK_VERIFY_ARG, gateforgeHookScript, hasGateforgeMarker, resolveHooksDir, verifyHookActivation } from './staged-candidate.js';

export { HOOK_MARKER_BEGIN, HOOK_MARKER_END, HOOK_VERIFY_ARG, gateforgeHookScript, hasGateforgeMarker, resolveHooksDir, verifyHookActivation };

/** Name of the hook Git runs before a commit is created. */
export const PRE_COMMIT_HOOK_NAME = 'pre-commit';
/** Name of the hook Git runs before a ref update is pushed. */
export const PRE_PUSH_HOOK_NAME = 'pre-push';
/** Marker lines delimiting Gateforge's pre-push hook. */
export const PRE_PUSH_MARKER_BEGIN = '# >>> gateforge pre-push v1 >>>';
/** End marker for the generated pre-push hook. */
export const PRE_PUSH_MARKER_END = '# <<< gateforge pre-push v1 <<<';

/**
 * The standalone staged-gate runner written under `.gateforge/hooks/`:
 * consumers with a foreign hook manager chain it manually (the exact
 * action the conflict report names), and it doubles as the verify target
 * for `check`-less environments. Same engine resolution and strict gate
 * as the generated pre-commit hook.
 */
export const STAGED_GATE_SCRIPT_BASENAME = 'gateforge-staged.sh';

/** The typed outcome of one `init --blocking` hook installation. */
export type HookInstallOutcome =
  | { status: 'installed'; hookPath: string; hooksDir: string; detail: string }
  | { status: 'updated'; hookPath: string; hooksDir: string; detail: string }
  | { status: 'verified'; hookPath: string; hooksDir: string; detail: string }
  | { status: 'framework'; hookPath: string; hooksDir: string; detail: string }
  | { status: 'conflict'; hookPath: string; hooksDir: string; detail: string; action: string }
  | { status: 'incomplete'; hookPath: string | null; hooksDir: string | null; detail: string; action: string };

/** Signatures of a pre-commit-FRAMEWORK-managed hook (pre-commit install
 * regenerates this file from .pre-commit-config.yaml on every run, so any
 * direct edit to it — including gateforge's — would be silently wiped). */
const FRAMEWORK_HOOK_MARKERS = ['File generated by pre-commit', '-mpre_commit'];

/**
 * Whether a `.git/hooks/pre-commit` body was generated by a pre-commit
 * FRAMEWORK rather than hand-written. Such a file carries no Gateforge
 * marker by construction — the framework rewrites it from
 * `.pre-commit-config.yaml` on every install — so every surface that
 * asks "is the gate wired here?" has to ask this question instead of
 * reading for our marker, or it reports a working setup as untouched.
 *
 * Exported so `enforcement doctor` and the installer answer with the
 * same rule instead of two drifting marker lists.
 *
 * Args:
 *   body: the hook file's contents.
 *
 * Returns:
 *   boolean: true when the file is framework-managed.
 */
export function isFrameworkManagedHookBody(body: string): boolean {
  return FRAMEWORK_HOOK_MARKERS.some((marker) => body.includes(marker));
}

/**
 * Installs (or verifies) the active pre-commit hook (plan Phase 5 item
 * 1). Writing the hook is not enough: after writing or finding a
 * gateforge-owned hook the activation is VERIFIED — exec bit present and
 * the script actually executes its verify mode.
 *
 * Args:
 *   cwd: absolute repository root.
 *   env: process environment.
 *
 * Returns:
 *   HookInstallOutcome: typed outcome; `conflict`/`incomplete` carry the
 *   exact required action and must be reported as an incomplete
 *   installation by the caller (nonzero exit).
 */
export function installCommitHook(
  cwd: string,
  env: NodeJS.ProcessEnv,
  gateArgs: readonly string[] = ['check', '--staged', '--require-e2e'],
): HookInstallOutcome {
  const hooksDir = resolveHooksDir(cwd, env);
  if (hooksDir === null) {
    return {
      status: 'incomplete',
      hookPath: null,
      hooksDir: null,
      detail: 'no usable Git repository found — the pre-commit hook could not be installed',
      action: 'Run `gateforge init --blocking` inside a Git repository work tree.',
    };
  }
  const hookPath = join(hooksDir, PRE_COMMIT_HOOK_NAME);
  if (existsSync(hookPath)) {
    const body = readFileSync(hookPath, 'utf8');
    if (hasGateforgeMarker(body)) {
      // Gateforge owns its marker block. Replace that block when the
      // requested mode changed, while preserving any foreign hook text
      // around it.
      const desired = gateforgeHookScript(gateArgs);
      const updatedBody = replaceGateforgeMarkerBlock(body, desired);
      const changed = updatedBody !== body;
      if (changed) writeFileSync(hookPath, updatedBody, 'utf8');
      try {
        if ((statSync(hookPath).mode & 0o111) === 0) chmodSync(hookPath, 0o755);
      } catch (error) {
        return {
          status: 'incomplete',
          hookPath,
          hooksDir,
          detail: `the gateforge hook could not be made executable: ${(error as Error).message}`,
          action: `Run: chmod +x ${hookPath}`,
        };
      }
      const verified = verifyHookActivation(hookPath);
      if (!verified.ok) {
        return {
          status: 'incomplete',
          hookPath,
          hooksDir,
          detail: `activation verification failed: ${verified.detail}`,
          action: `Inspect '${hookPath}' (it should contain the gateforge marker block and be executable), then re-run \`gateforge init --blocking\`.`,
        };
      }
      return {
        status: changed ? 'updated' : 'verified',
        hookPath,
        hooksDir,
        detail: changed
          ? `hook mode updated at '${hookPath}' (${gateArgs.join(' ')}); ${verified.detail}`
          : verified.detail,
      };
    }
    // Framework-managed hook: pre-commit install regenerates this file
    // from .pre-commit-config.yaml — chaining into it would be silently
    // wiped on the next `pre-commit install`. Gateforge integrates through
    // the framework config instead (the caller appends the gateforge hook
    // block there); activation = the framework config carries the hook.
    if (isFrameworkManagedHookBody(body)) {
      return {
        status: 'framework',
        hookPath,
        hooksDir,
        detail:
          'the existing pre-commit hook is framework-managed — gateforge wires itself through .pre-commit-config.yaml',
      };
    }
    // Foreign hook: NEVER clobber. Hand over the exact chaining action.
    const gateScript = join(cwd, '.gateforge', 'hooks', STAGED_GATE_SCRIPT_BASENAME);
    return {
      status: 'conflict',
      hookPath,
      hooksDir,
      detail:
        `an existing non-gateforge pre-commit hook was found at '${hookPath}'; ` +
        'gateforge never overwrites foreign hooks, so the commit gate is NOT active yet',
      action:
        `Add this line to the existing hook before it exits:\n` +
        `  "${gateScript}" || exit 1\n` +
        `then re-run \`gateforge init --blocking\` to verify activation.`,
    };
  }
  // Pre-commit FRAMEWORK without an installed hook: the framework
  // owns .git/hooks/pre-commit (it regenerates that file from
  // .pre-commit-config.yaml on every `pre-commit install`), so
  // gateforge must NEVER write a raw hook file here — it wires
  // itself through the framework config instead.
  const frameworkConfig = join(cwd, '.pre-commit-config.yaml');
  if (existsSync(frameworkConfig)) {
    return {
      status: 'framework',
      hookPath,
      hooksDir,
      detail:
        'pre-commit framework config found — gateforge wires itself through .pre-commit-config.yaml; ' +
        'run `pre-commit install` to activate the gate',
    };
  }
  const script = gateforgeHookScript(gateArgs);
  try {
    mkdirSync(hooksDir, { recursive: true });
    writeFileSync(hookPath, script, 'utf8');
    chmodSync(hookPath, 0o755);
  } catch (error) {
    return {
      status: 'incomplete',
      hookPath,
      hooksDir,
      detail: `the hook could not be written to '${hooksDir}': ${(error as Error).message}`,
      action: `Ensure '${hooksDir}' is writable by the current user, then re-run \`gateforge init --blocking\`.`,
    };
  }
  const verified = verifyHookActivation(hookPath);
  if (!verified.ok) {
    return {
      status: 'incomplete',
      hookPath,
      hooksDir,
      detail: `hook written but activation verification failed: ${verified.detail}`,
      action: `Inspect '${hookPath}', then re-run \`gateforge init --blocking\`.`,
    };
  }
  return {
    status: 'installed',
    hookPath,
    hooksDir,
    detail: `hook installed and ACTIVE at '${hookPath}' (exec bit set; verified invocation)`,
  };
}

/**
 * Installs the receipt-verification pre-push lane without replacing foreign hooks.
 *
 * Args:
 *   cwd: absolute repository root.
 *   env: process environment used to resolve Git's hooks directory.
 *
 * Returns:
 *   HookInstallOutcome: installed, verified, conflict, or incomplete state.
 */
export function installPrePushHook(cwd: string, env: NodeJS.ProcessEnv): HookInstallOutcome {
  const hooksDir = resolveHooksDir(cwd, env);
  if (hooksDir === null) {
    return {
      status: 'incomplete',
      hookPath: null,
      hooksDir: null,
      detail: 'no usable Git repository found — the pre-push hook could not be installed',
      action: 'Run `gateforge init --blocking` inside a Git repository work tree.',
    };
  }
  const hookPath = join(hooksDir, PRE_PUSH_HOOK_NAME);
  const script = prePushHookScript();
  if (existsSync(hookPath)) {
    const current = readFileSync(hookPath, 'utf8');
    if (!current.includes(PRE_PUSH_MARKER_BEGIN) || !current.includes(PRE_PUSH_MARKER_END)) {
      return {
        status: 'conflict',
        hookPath,
        hooksDir,
        detail: `a foreign pre-push hook exists at '${hookPath}'; Gateforge did not overwrite it`,
        action: `Add a pre-push stdin loop that runs \`gateforge check --candidate-commit "$local_sha" --require-e2e\` for each non-deletion local SHA, then re-run \`gateforge init --blocking\`.`,
      };
    }
    const verify = probeHookExecution(hookPath);
    if (!verify.ok) {
      return {
        status: 'incomplete',
        hookPath,
        hooksDir,
        detail: `pre-push activation verification failed: ${verify.detail}`,
        action: `Inspect '${hookPath}' and re-run \`gateforge init --blocking\`.`,
      };
    }
    return { status: 'verified', hookPath, hooksDir, detail: `pre-push hook active at '${hookPath}'` };
  }
  try {
    mkdirSync(hooksDir, { recursive: true });
    writeFileSync(hookPath, script, 'utf8');
    chmodSync(hookPath, 0o755);
  } catch (error) {
    return {
      status: 'incomplete',
      hookPath,
      hooksDir,
      detail: `the pre-push hook could not be written to '${hooksDir}': ${(error as Error).message}`,
      action: `Ensure '${hooksDir}' is writable, then re-run \`gateforge init --blocking\`.`,
    };
  }
  const verify = probeHookExecution(hookPath);
  if (!verify.ok) {
    return {
      status: 'incomplete',
      hookPath,
      hooksDir,
      detail: `pre-push hook written but activation verification failed: ${verify.detail}`,
      action: `Inspect '${hookPath}' and re-run \`gateforge init --blocking\`.`,
    };
  }
  return { status: 'installed', hookPath, hooksDir, detail: `pre-push hook installed and active at '${hookPath}'` };
}


/**
 * Renders the pre-push hook that verifies every non-deletion local ref tip.
 *
 * Returns:
 *   string: executable POSIX shell source.
 */
function prePushHookScript(): string {
  return `#!/bin/sh
${PRE_PUSH_MARKER_BEGIN}
if [ "$1" = "${HOOK_VERIFY_ARG}" ]; then
  echo "gateforge: pre-push receipt lane active"
  exit 0
fi
GF_BIN=""
if [ -f "node_modules/.bin/gateforge" ]; then
  GF_BIN="node_modules/.bin/gateforge"
elif command -v gateforge >/dev/null 2>&1; then
  GF_BIN="gateforge"
fi
if [ -n "$GATEFORGE_CLI" ] && [ -x "$GATEFORGE_CLI" ]; then
  GF_BIN="$GATEFORGE_CLI"
fi
if [ -z "$GF_BIN" ]; then
  echo "gateforge: CLI engine not found; push blocked (fail closed)" >&2
  exit 1
fi
unset GIT_DIR GIT_WORK_TREE GIT_INDEX_FILE GIT_PREFIX
while IFS=' ' read -r local_ref local_sha remote_ref remote_sha
do
  case "$local_sha" in
    *[!0]*) ;;
    *) continue ;;
  esac
  case "$GF_BIN" in
    */*) node "$GF_BIN" check --candidate-commit "$local_sha" --require-e2e ;;
    *) "$GF_BIN" check --candidate-commit "$local_sha" --require-e2e ;;
  esac || exit $?
done
${PRE_PUSH_MARKER_END}
`;
}
/**
 * Writes the standalone staged-gate script under `.gateforge/hooks/`
 * (idempotent, executable) — the chaining target the conflict report
 * names and a manual-verification entry point.
 *
 * Args:
 *   cwd: absolute repository root.
 *
 * Returns:
 *   string: absolute path of the script.
 *
 * Throws:
 *   Error: when the script cannot be written (caller reports incomplete).
 */
export function writeStandaloneGateScript(
  cwd: string,
  gateArgs: readonly string[] = ['check', '--staged', '--require-e2e'],
): string {
  const dir = join(cwd, '.gateforge', 'hooks');
  mkdirSync(dir, { recursive: true });
  const path = join(dir, STAGED_GATE_SCRIPT_BASENAME);
  let gateforgeOwned = true;
  if (!existsSync(path)) {
    writeFileSync(path, gateforgeHookScript(gateArgs), 'utf8');
  } else {
    const current = readFileSync(path, 'utf8');
    if (hasGateforgeMarker(current)) {
      const updated = replaceGateforgeMarkerBlock(current, gateforgeHookScript(gateArgs));
      if (updated !== current) writeFileSync(path, updated, 'utf8');
    } else gateforgeOwned = false;
  }
  if (gateforgeOwned) {
    try {
      chmodSync(path, 0o755);
    } catch {
      // A non-executable standalone script still fails activation checks;
      // the hook installation path reports the honest state.
    }
  }
  return path;
}

/**
 * Inspects the hook state for `enforcement doctor` (plan Phase 5 item
 * 7): hooks directory, hook presence, gateforge marker, exec bit, and
 * verified activation — reported honestly, never as managed protection.
 *
 * Args:
 *   cwd: absolute repository root.
 *   env: process environment.
 *
 * Returns:
 *   {installed, hooksDir, hookPath, marker, execBit, verifyOk, detail}:
 *   the honest inspection record.
 */
export function inspectCommitHook(
  cwd: string,
  env: NodeJS.ProcessEnv,
): {
  installed: boolean;
  hooksDir: string | null;
  hookPath: string | null;
  marker: boolean;
  execBit: boolean;
  verifyOk: boolean;
  detail: string;
} {
  const hooksDir = resolveHooksDir(cwd, env);
  if (hooksDir === null) {
    return {
      installed: false,
      hooksDir: null,
      hookPath: null,
      marker: false,
      execBit: false,
      verifyOk: false,
      detail: 'no usable Git repository — hooks directory could not be resolved',
    };
  }
  const hookPath = join(hooksDir, PRE_COMMIT_HOOK_NAME);
  if (!existsSync(hookPath)) {
    return {
      installed: false,
      hooksDir,
      hookPath,
      marker: false,
      execBit: false,
      verifyOk: false,
      detail: `no pre-commit hook exists at '${hookPath}' (run \`gateforge init --blocking\`)`,
    };
  }
  const body = readFileSync(hookPath, 'utf8');
  const marker = hasGateforgeMarker(body);
  const execBit = (statSync(hookPath).mode & 0o111) !== 0;
  const verified = verifyHookActivation(hookPath);
  const detail = marker
    ? verified.ok
      ? verified.detail
      : `installed but NOT active: ${verified.detail}`
    : execBit
      ? `a non-gateforge pre-commit hook exists at '${hookPath}' (no gateforge marker; gateforge did not touch it)`
      : `a non-gateforge pre-commit hook exists at '${hookPath}' (no gateforge marker, not executable)`;
  return { installed: marker && execBit, hooksDir, hookPath, marker, execBit, verifyOk: verified.ok, detail };
}

/** Replaces only the Gateforge-owned marker block in a direct Git hook. */
function replaceGateforgeMarkerBlock(body: string, replacement: string): string {
  const begin = body.indexOf(HOOK_MARKER_BEGIN);
  const end = body.indexOf(HOOK_MARKER_END);
  if (begin < 0 || end < begin) return replacement;
  const suffix = body.slice(end + HOOK_MARKER_END.length);
  const joinedReplacement = replacement.endsWith('\n') && suffix.startsWith('\n') ? replacement.slice(0, -1) : replacement;
  return `${body.slice(0, begin)}${joinedReplacement}${suffix}`;
}

/**
 * One-shot activation probe used by tests and the doctor: runs the hook
 * script's verify mode directly (proves the exec bit + the shebang work
 * without a commit).
 *
 * Args:
 *   hookPath: absolute hook path.
 *
 * Returns:
 *   {ok, detail}: spawn result (spawnSync is used directly here so a
 *   spawn-level failure surfaces as `ok: false`, never an exception).
 */
export function probeHookExecution(hookPath: string): { ok: boolean; detail: string } {
  const run = spawnSync(hookPath, [HOOK_VERIFY_ARG], { encoding: 'utf8', timeout: 10_000 });
  if (run.error !== undefined || run.status !== 0) {
    return { ok: false, detail: `hook did not execute (exit ${run.status ?? -1})` };
  }
  return { ok: true, detail: run.stdout.trim() };
}
